### ISSUE TITLE
"Play" button displayed when resetting back to last PhET-iO state

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#211] opened 2020-08-28 00:18 UTC
I'm pretty sure this is a bug, and likely easy to fix. It is discontinuity between when you set a phet-io state, and then when you reset back to that same state.

To reproduce:
1. studio
2. add a mate and wait at least 1 generation
3. pause the sim
4. launch the sim (in studio) to a new wrapper. This will set that state on a new sim instance.
5. Once fully loaded, press the reset all button. 
6. Nothing changes except a yellow "Play" button shows in the environment view:

![image](https://user-images.githubusercontent.com/6856943/91507289-e8f43d80-e880-11ea-89fe-1f8633f9dd98.png)

Perhaps there is just one thing that isn't being handled by state? What do you think @pixelzoom?

**Comment by pixelzoom** [comment] 2020-08-28 00:46
Yep. Unfortunately this was introduced by https://github.com/phetsims/natural-selection/commit/645d60d0fc839399fef4916b608b6214307592f8 for #166, where I addressed the "double-click on Start Over button" problem.  Since it's specific to PhET-iO and the prototype is brand=phet only, we can definitely defer this until after the prototype.

**Comment by pixelzoom** [comment] 2020-08-28 02:14
@zepumph How did you happen to notice this problem? I see a CT failure at 3:52PM today, but it doesn't seem related:

> phet-io-mirror-inputs-fuzz : unbuilt
> ...
> Uncaught Error: Uncaught Error: Assertion failed: there should only be 1 live bunny

**Comment by zepumph** [comment] 2020-08-28 06:45
I tested NS in the state wrapper (you can reproduce with the "launch" button there too, as part of the review in https://github.com/phetsims/phet-io/issues/1654#issuecomment-681118825.

**Comment by pixelzoom** [comment] 2020-09-02 20:06
Reproduced in master following the steps in https://github.com/phetsims/natural-selection/issues/211#issue-687621572.

**Comment by pixelzoom** [comment] 2020-09-02 20:59
This was resolved by reverting the change to PlayButtonGroup.js for #217.  I'll find another way to address that issue that plays nice with PhET-iO state.

Closing.

**Closed by pixelzoom** 2020-09-02 20:59 UTC
Labels: dev:phet-io, status:blocks-sim-publication, type:bug
