### ISSUE TITLE
CT: expected selectionRectangleSpriteInstance in spriteInstances

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#132] opened 2020-07-16 14:48 UTC
```
natural-selection : fuzz : unbuilt : query-parameters
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22query-parameters%22%5D%2C%22snapshotName%22%3A%22snapshot-1594908797132%22%2C%22timestamp%22%3A1594910025365%7D&brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Query: brand=phet&ea&fuzz&memoryLimit=1000&allelesVisible=false&introMutations=F&introPopulation=10Ff&labMutations=FeT&labPopulation=2FFeett,2ffEEtt,2ffeeTT
Uncaught Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
Error: Assertion failed: expected selectionRectangleSpriteInstance in spriteInstances
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/assert/js/assert.js:22:13)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:325:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:178:71
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/axon/js/Property.js:171:14)
at SelectedBunnyProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/axon/js/Property.js:336:10)
at BunnyCollection.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/js/common/model/BunnyCollection.js:163:32)
at IntroModel.startOver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/js/common/model/NaturalSelectionModel.js:233:26)
at IntroModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594908797132/natural-selection/js/common/model/NaturalSelectionModel.js:213:10)
id: Bayes Chrome
Snapshot from 7/16/2020, 8:13:17 AM
```

**Comment by pixelzoom** [comment] 2020-07-16 15:49
Related to the reimplementation using sprites in #128.

**Comment by pixelzoom** [comment] 2020-07-20 18:55
The problem here is that the selection rectangle continues to exist after the selected bunny has died.  This was also reported in #137.

Steps to reproduce:

1. Start sim, go to either screen.
2. Select the lone bunny
3. Press "Add a Mate"
4. Wait for the selected bunny to die at generation 5. Note that the bunny disappears and the selection rectangle remains.

This should be a relatively easy fix.  I forgot that `selectedBunnyProperty` is not set to null when a bunny dies - the bunny remains selected and displayed in the Pedigree graph.   So I'll need to add a listener to the selected bunny's `diedEmitter`, and manage that listener when the selection changes or the bunny dies.

**Comment by pixelzoom** [comment] 2020-07-20 19:10
#132 and #133 had the same root cause -- incorrect handling of `selectedBunnyProperty`.  Fixed in the above commit.  I'll wait to close until I verify that CT is happy.

**Comment by pixelzoom** [comment] 2020-07-20 22:36
Still not fixed :(

**Comment by pixelzoom** [comment] 2020-07-20 22:39
This is now manifesting as errors like:

```
natural-selection : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595283006851%22%2C%22timestamp%22%3A1595284357201%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
Error: Assertion failed: number of bunny sprites 3 is out of sync with number of bunnies 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/assert/js/assert.js:22:13)
at NaturalSelectionSprites.assertBunniesInSync (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:443:15)
at NaturalSelectionSprites.sort (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:412:22)
at NaturalSelectionSprites.update (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:210:10)
at NaturalSelectionSprites.setSelectedBunny (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:352:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/natural-selection/js/common/view/environment/NaturalSelectionSprites.js:179:63
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/axon/js/TinyEmitter.js:69:53)
at SelectedBunnyProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/axon/js/Property.js:273:25)
at SelectedBunnyProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/axon/js/Property.js:171:14)
at SelectedBunnyProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595283006851/axon/js/Property.js:343:32)
id: Bayes Chrome
Snapshot from 7/20/2020, 4:10:06 PM
```

**Comment by pixelzoom** [comment] 2020-07-22 03:22
This issue and #136 had the same root cause. There was a bug in NaturalSelectionSprites `sort` that took me forever to find, fixed in https://github.com/phetsims/natural-selection/commit/cdc84e8ff63e9bc4ad2747fa8161f19022e4e9ed.   I think that should do it, but will wait for a few CT cycles before closing.

**Comment by pixelzoom** [comment] 2020-07-22 16:18
There's a new issue in CT, but this one is gone.  Closing.

**Closed by pixelzoom** 2020-07-22 16:18 UTC
Labels: status:ready-for-review, type:automated-testing
