### ISSUE TITLE
Uninstrument Text and RichText

### ISSUE THREAD

**Issue by arouinfar** [phetsims/natural-selection#339] opened 2023-07-21 23:12 UTC
For #323 

Issues identified in https://github.com/phetsims/studio/issues/303 lead to a new way to autoselect strings in Studio. As a result, the recommendation in https://github.com/phetsims/phet-io/issues/1941 is that most instances of text do not need to be instrumented. 

@pixelzoom subsequently uninstrumented text in other sims like https://github.com/phetsims/molecule-polarity/issues/160 and https://github.com/phetsims/graphing-quadratics/issues/187. Seems like we should do the same in Natural Selection. Do you agree @pixelzoom?

**Comment by pixelzoom** [comment] 2023-07-21 23:25
Yes agreed.

**Comment by pixelzoom** [comment] 2023-07-22 15:24
In the above commits, I uninstrumented Text (there are no RichText) and updated the API file.   The next step will be to add migration rules.  Before I do that, I'd like @arouinfar to review in Studio.   Please assign back to me after review.

**Comment by pixelzoom** [comment] 2023-07-22 15:29
All of these Text elements were apparently instrumented since the 1.4 release, so they were never part of a published API.  Therefore no migration rules are needed, as confirmed via the Migration wrapper.   Great call on uninstrumenting these @arouinfar. Feel free to close this issue if everything looks good in Studio.

**Comment by pixelzoom** [comment] 2023-07-25 16:32
@arouinfar Both of the "text" elements that you've identified above are in common code. `view.dialogs.memoryLimitDialog.text` is in OopsDialog.  `generationSpinner.numberDisplay.valueText` is in NumberDisplay. If I remove those, it will change the API of all sims, and require migration rules for all sims.  

I recommend that we leave this "as is" for Natural Selection.  And optionally open issue(s) to uninstrument Text/RichText in common code. @arouinfar thoughts?

**Comment by pixelzoom** [comment] 2023-07-25 17:30
> ... And optionally open issue(s) to uninstrument Text/RichText in common code.  ...

See https://github.com/phetsims/phet-io/issues/1952

**Comment by arouinfar** [comment] 2023-07-25 17:44
> I recommend that we leave this "as is" for Natural Selection. And optionally open issue(s) to uninstrument Text/RichText in common code. @arouinfar thoughts?

Agreed @pixelzoom. Thanks for opening https://github.com/phetsims/phet-io/issues/1952! Closing.

**Comment by pixelzoom** [comment] 2023-07-27 19:39
Reopening. Over in https://github.com/phetsims/phet-io/issues/1952, we decided to address NumberDisplay and OopsDialog for Natural Selection 1.5.

**Comment by pixelzoom** [comment] 2023-07-28 19:32
In the above commits, I uninstrumented RichText in OopsDialog.  This was easy because natural-selection-phet-api.json is the only API that contained this element, and it was added since the 1.4 release, so could be removed without a migration rule.

**Comment by pixelzoom** [comment] 2023-07-28 19:32
In the above commits, I uninstrumented RichText in OopsDialog. This was easy because natural-selection-phet-api.json is the only API that contained this element, and it was added since the 1.4 release, so could be removed without a migration rule.

**Comment by pixelzoom** [comment] 2023-07-28 21:48
NumberDisplay quickly turned into a nightmare. `numberDisplay.valueText.stringProperty` is missing the string pattern dependency, so there's much more work to be done in NumberDisplay than just uninstrument numberDisplay.valueText -- see https://github.com/phetsims/scenery-phet/issues/812.

So for this sim, I simply uninstrumented `generationSpinner.numberDisplay`.  The Studio tree used to look like this:

<img width="206" alt="screenshot_2680" src="https://github.com/phetsims/natural-selection/assets/3046552/d6f9dbdb-2eeb-4cd6-8659-3835bd883d99">

... and now it looks like this:

<img width="210" alt="screenshot_2681" src="https://github.com/phetsims/natural-selection/assets/3046552/5cc96d09-b0fd-4854-a355-cadf0e9f9004">

This seems OK to me for now. There's really no reason to make the `numberDisplay` invisible (its `visibleProperty` probably should have been readonly).  And all of the info is available elsewhere.  And we have not instrumented the other NumberDisplay instance in this sim, whcih would have been `populationGraphNode.dataProbeNode.numberDisplay`.

@arouinfar Please review.  To summarize:

* `memoryLimitDialog.text` was uninstrumented
* `memoryLimitDialog.memoryLimitMessageStringProperty` has been added
* `generationSpinner.numberDisplay` was uninstrumented

**Comment by arouinfar** [comment] 2023-07-31 15:20
Thanks @pixelzoom. The updates and tree structure look great.

I noticed that toggling `generationSpinner.visibleProperty` can create layout issues. 
<img width="501" alt="image" src="https://github.com/phetsims/natural-selection/assets/8419308/da142c61-750b-44df-b18b-f835e1c9ab28">

I don't remember seeing this before, but I might of missed it. Not sure if this is related to the changes made to `generationSpinner` here or if this is entirely unrelated issue.

**Closed** 2023-07-31 16:16 UTC
Labels: dev:phet-io, status:ready-for-review
