### ISSUE TITLE
CT cannot read property generation of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#73] opened 2020-05-08 14:52 UTC
```
natural-selection : phet-io-state-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588900082851%22%2C%22timestamp%22%3A1588940333072%7D
Uncaught Error: Cannot read property 'generation' of null
TypeError: Cannot read property 'generation' of null
at Function.fromStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/natural-selection/js/common/model/Bunny.js:345:57)
at Function.fromStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/natural-selection/js/common/model/BunnyIO.js:36:18)
at Function.addChildElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/tandem/js/PhetioGroupIO.js:67:35)
at PhetioStateEngine.tryToCreateAncestor (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:555:51)
at PhetioStateEngine.tryToCreateAncestor (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:568:12)
at PhetioStateEngine.tryToCreateAncestor (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:568:12)
at PhetioStateEngine.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:511:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:421:31
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/phet-io/js/PhetioStateEngine.js:410:22)
id: Bayes Chrome
Snapshot from 5/7/2020, 7:08:02 PM
```

**Comment by pixelzoom** [comment] 2020-05-08 15:51
I can't reproduce this locally, and CT is now showing green.  It was a problem for 2 CT cycles yesterday, 5:36pm and 7:08pm.  @samreid and @chrisklus don't know of any related iO problem that was fixed > 7:08pm.  @zepumph?

**Comment by zepumph** [comment] 2020-05-08 16:37
It doesn't ring any bells! I don't see any suspicious commits in `tandem/` or `phet-io/` from around that time. Very strange. 

Yesterday I was working on this exact code, but I only made a patch, I didn't commit. The bug that you encountered above should never happen again after we clean up `PhetioStateEngine.tryToCreateAncestor` over in https://github.com/phetsims/phet-io/issues/1634#issuecomment-625515116 (second bullet with action step (3)). If this doesn't show up again, Think we should close this, but I don't see why it wouldn't keep showing up given enough CT time to complete a generation or two. I'll keep myself assigned.

**Comment by pixelzoom** [comment] 2020-05-08 17:45
This occurred again at 5/8/2020 10:47am.

**Comment by pixelzoom** [comment] 2020-05-08 17:52
Yesterday I added this DerivedProperty to Genotype:

```js
    // @public PhET-iO only, not used in the sim
    // eslint-disable-next-line no-new
    new DerivedProperty( [...], (...) => {
        ...
      }, {
        tandem: options.tandem.createTandem( 'geneotypeAbbreviationProperty' ),
        phetioType: DerivedPropertyIO( StringIO ),
        phetioDocumentation: 'the abbreviation that describes the genotype, the empty string if there are no dominant alleles'
      } );
```

I see that I neglected to dispose this Property when Genotype is disposed.  If that's the cause of this problem, this Error message is not at all helpful.

**Comment by pixelzoom** [comment] 2020-05-08 22:54
That appears to have fixed the problem, it's no longer occurring in CT.  But I don't understand why it fixed the problem, why it manifested as a `null` arg to Bunny.fromStateObject. @zepumph any insight?

**Comment by zepumph** [comment] 2020-05-13 18:08
I do not know either! I'm kicking myself for waiting this long to answer this question, because now when I comment out the `dispose` call for `Genotype.prototype.abbreviationProperty`, I get the following error:

```
Assertion failed: phetioID already registered: naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_0.genotype.abbreviationProperty
```
Which seems much more reasonable to me.

I do not know how to proceed in debugging the weird logic from last week, nor do I know what the priority is for that. 

For the future, note that my go-to, phet-io debugging tool for random, seemingly outrageous, or vague errors is the following patch. This can help catch a non-assert errors done through the phet-io API. 

```diff
Index: js/phetioCommandProcessor.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phetioCommandProcessor.js	(revision 97c59f3e1961b38837f45be471bdf4b2b66c3654)
+++ js/phetioCommandProcessor.js	(date 1589393049342)
@@ -160,6 +160,7 @@
         return { returnValue: this.processCommand( targetWindow, command ), error: null };
       }
       catch( error ) {
+        debugger;
 
         // Catch error during invocation and return them to the caller, and take serializable parts.
         return { returnValue: null, error: { message: error.message, stack: error.stack } };

```
It is a slightly worse solution from running chrome dev tools with "pause on caught exceptions" enabled (though that can get annoying generally).

Over to you to close.

**Comment by pixelzoom** [comment] 2020-05-13 18:13
OK, thanks for having a look.  Closing.

**Closed by pixelzoom** 2020-05-13 18:13 UTC
Labels: type:automated-testing
