### ISSUE TITLE
Mirror input thrown off if mouse leaves upper iframe.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#264] opened 2021-04-05 22:42 UTC
For https://github.com/phetsims/QA/issues/636. May be related to recent iframe changes. I think I may have also seen something like this in the record wrapper where events didn't match what I did for a while, but I'm not sure if this could cause that. I'll keep trying to reproduce that one.
For this issue, if you zoom in and use the mouse to start panning around, and your mouse leaves the upper iframe and lets go, then coming back will stop panning in the upper frame but not the lower pane. I suspect something similar would happen for other draggable objects, but this sim has few of them.
![mirroriframeoff](https://user-images.githubusercontent.com/41024075/113635418-d4a1cb80-962d-11eb-8c03-465cefbb008e.gif)

**Comment by KatieWoe** [comment] 2021-04-05 22:42
@pixelzoom let me know if you want me to move this to a different repo.

**Comment by KatieWoe** [comment] 2021-04-05 22:49
I did some more testing and it seems like this does happen in the recording wrapper as well.

**Comment by pixelzoom** [comment] 2021-04-05 22:53
This doesn't seem at all specific to the sim.  Assigning to the PhET-iO team to investigate.  If this is indeed a general problem, please create a general GitHub issue in the appropriate repo.

**Comment by zepumph** [comment] 2021-04-06 01:22
@jonathanolson what action/event from input is not being properly captured by the downstream system? Presumably it is something that is interrupting the pointer in the upstream. Is there anything more that lostPointerCaptureAction or gotPointerCaptureAction? If not perhaps it is that the event doesn't look as we suspect. I'll investigate.

**Comment by jonathanolson** [comment] 2021-04-06 18:17
I'm reproducing in master. With `?sceneryLog=Input`, I am seeing lost pointer capture:

```
[Input] lostPointerCapture('1',26881.969999987632 lostpointercapture);
```

Investigating

**Comment by jonathanolson** [comment] 2021-04-06 18:31
I've identified the cause. The code that sets the pointer ID on the mouse (`this.mouse.id = id;`) is in `pointerDown`, which is outside of the actions, and isn't run on playback.

It seems the playback system is based on higher-level abstractions than are probably desired longer-term for playback (we'd really want to record things at the event level for accurate playback, e.g. there are three different events that can trigger a mouseDown action, but we only record the mouseDown). NOTE: This would be less than ideal presumably for a usable event stream.

I'll look into less invasive workarounds for now.

**Comment by jonathanolson** [comment] 2021-04-06 18:36
The best change from my perspective would be adding an optional `id` parameter (number or null) to `mouseDownAction` (and `mouseDown()`), which would be used in the code to set the mouse's ID. `mouseUp` would also need to be modified to clear this ID.

This sounds like it would break backward compatibility to event recording. @zepumph thoughts?

@pixelzoom, do you know the priority for this work?

**Comment by pixelzoom** [comment] 2021-04-06 18:43
> @pixelzoom, do you know the priority for this work?

Priority is high.  The goal is complete dev test phetsims/QA#636 as quickly as possible (in the next day or two), and then immeditely create a release branch before changes sneak into master.

**Comment by pixelzoom** [comment] 2021-04-06 18:45
> @pixelzoom, do you know the priority for this work?

Priority is high.  The goal is to complete dev test phetsims/QA#636 as quickly as possible (in the next day or two), and then immediately create a release branch before changes sneak into master. 

Since this is a dev test, there is no release branch that needs to be patched.  But if this is deemed a blocking issue, the problem will need to be resolved in master before the release branch can be created.   You'll have to ask @kathy-phet and @amanda-phet whether this is a blocking issue.

**Comment by jonathanolson** [comment] 2021-04-06 19:10
Hopped on a call with @zepumph and we determined that the ideal long-term solution was adding the optional ID to mouseDown/mouseDownAction. There is a whole host of low level code that should NOT run in playback, so I believe the actions ARE at the correct abstraction level.

Fixes are above. @KatieWoe can you verify in master?

**Comment by KatieWoe** [comment] 2021-04-06 19:47
It looks like this is solved on master

**Comment by jonathanolson** [comment] 2021-04-06 20:57
Perfect! Closing.

**Closed by jonathanolson** 2021-04-06 20:57 UTC
Labels: dev:phet-io, type:bug
