### ISSUE TITLE
Reset All in launched sim creates "Add a Mate" button when it shouldn't

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#235] opened 2020-09-21 22:59 UTC
**Device**
Personal Mac Air
**OS**
Mac OS 10.15.6
**Browser**
Chrome 85.0.4183.102
**Problem Description**
For https://github.com/phetsims/QA/issues/551.
If you launch a sim in a state different from default (specifically with more than one rabbit) and then hit the reset all button the "add a mate" button appears when it shouldn't. Pressing it doesn't seem to make it go away.
**Steps to Reproduce:**
1. In Studio, go to the second screen and press "add a mate"
2. After a few more bunnies show up, pause the sim
3. Launch the sim
4. Hit reset all

**Visuals**
https://drive.google.com/file/d/1EOm7XDSKyAqJ-2SK8dvDAcAToKIggn-A/view?usp=sharing

**Comment by pixelzoom** [comment] 2020-09-21 23:13
Reproduced in 1.2.0-rc.1 and master.

**Comment by pixelzoom** [comment] 2020-09-22 19:08
Between 1.1.0-dev.16 and 1.1.0-dev.17, a similar problem was introduced where the "Play" button would be visible after pressing the Reset All button.  That problem was fixed in 5b373bf9d8ee548a86194fcb846e6a8627d86e0c for #217 between 1.2.0-dev.1 and 1.2.0-dev.2. 

Between 1.2.0-dev.2 and 1.2.0-dev.3, the problem described in this issue was introduced.

**Comment by pixelzoom** [comment] 2020-09-22 19:23
The problem is related to https://github.com/phetsims/natural-selection/issues/217 (double-click of Start Over button).  I'm really wishing we had just ignored that problem, because the solution keeps causing other problems.  The solution was to make the "Add a Mate" (or "Play") button visible in the next frame, by using a timer.  In this case in the State Wrapper, the value of simulationModeProperty (which determines which buttons are visible) changes before the timer fires, and a button is then incorrectly made visible.  This can never happen when running the sim normally -- it's yet-another "gotta do this special for restoring state" problem.

**Comment by pixelzoom** [comment] 2020-09-22 19:29
Fixed in the master and 1.2 in the above commits and cherry-picks.  This required checking simulationModeProperty again in the callback, i.e.:

```js
          stepTimer.runOnNextTick( () => {

             // Checking simulationModeProperty to make sure it hasn't changed again before this callback fires.
             // See https://github.com/phetsims/natural-selection/issues/235
             if ( simulationModeProperty.value === SimulationMode.STAGED ) {
               addAMateButton.visible = ( bunnyCount === 1 );
               playButton.visible = ( bunnyCount > 1 );
             }
           } );
```

**Comment by pixelzoom** [comment] 2020-09-24 02:10
Ready for testing in the next 1.2 RC.

**Comment by phet-steele** [comment] 2020-09-25 22:08
Been testing 1.2.0-rc.2 with Win 10 Chrome, and I haven't been able to reproduce this issue.

**Closed by phet-steele** 2020-09-25 22:08 UTC
Labels: dev:phet-io, status:ready-for-qa, type:bug
