### ISSUE TITLE
iPadOS 13 crashes and reloads

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#286] opened 2021-06-29 18:16 UTC
For https://github.com/phetsims/QA/issues/662
iPadOS 13.7 Safari, the sim crashed and reloaded fairly quickly (phet-brand). The device hadn't been used in a while and restarting it seems to have improved the issue, but a crash did happen again. First was with `?stringTest=double` and second was with `stringTest=rtl`. Nothing in particular seemed to precede the crashes, just normal usage.
Not sure what next steps would be since the memory tests looked ok.

**Comment by pixelzoom** [comment] 2021-06-30 20:33
@KatieWoe please identify the device, and attempt to reproduce.  If unable to reproduce, then you can close this issue.

**Comment by KatieWoe** [comment] 2021-06-30 20:35
It was an iPadAir 2 running iPadOS 13.7. It did occur twice (reproduced from https://github.com/phetsims/QA/issues/662#issuecomment-870789959) which is when I added it here. Do you want me to try for another reproduction?

**Comment by pixelzoom** [comment] 2021-06-30 20:43
Yes please. If you can tether the iPadAir to a Mac, and get console output, that would be very useful. Otherwise I have no idea how I'd proceed with investigating this.

**Comment by KatieWoe** [comment] 2021-06-30 20:45
Alright. May be a bit before I get the chance to try. I'll let you know if I manage to reproduce with a console.

**Comment by KatieWoe** [comment] 2021-07-01 19:46
Tried for about half an hour and wasn't able to reproduce with the console. @pixelzoom let me know if you want me to keep trying.

**Comment by pixelzoom** [comment] 2021-07-01 20:08
Let's assume that this was something specific to this device, and close this issue.  If it reoccurs, we can reopen.

**Closed by pixelzoom** 2021-07-01 20:08 UTC
Labels: type:performance
