### ISSUE TITLE
Change request: don't apply limited food if population is < 7

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#153] opened 2020-08-03 15:53 UTC
MH said:
>If I turn in Limited Food in the parental generation, they both die immediately.  If I turn it on in the first generation (i.e. after one birthing round), the population stays very low and dies out in a few generations.  Is this intentional?  It seems that if there is limited food but still some food available, the population should survive long-term but stay small.

MH is saying that without any predators, the bunnies should be able to sustain a small population. However, if we kill ~2/3 of the bunnies, and there are only 3-4 alive, the bunnies are likely to die out. So let's apply apply a similar rule as #152  and say limited food doesn't kill any bunnies if the population is under 7.

**Comment by pixelzoom** [comment] 2020-08-03 20:20
Limited food no longer contributes to starvation when the total population size is < 7. Changed in master and 1.0 branch.  

@amanda-phet please verify in master or [1.1.0-dev.2](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.2/phet/natural-selection_en_phet.html). Please assign back to me after reviewing.

**Comment by oliver-phet** [comment] 2020-08-04 16:23
I'll try to reproduce, but I was just able to get population to die out (only Limited Food was selected, but long teeth mutation was added). Last generation was 7 bunnies and 6 died:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/5090275/89317083-24ad3600-d63a-11ea-9a9d-3dff6c5020f1.png">

**Comment by pixelzoom** [comment] 2020-08-04 16:28
@oliver-phet Please clarify.  I see 1 bunny still alive in the above screenshot. How is that getting the population to die out?  

I sounds like this is working as requested. 7 bunnies is not < 7, so limited food will be applied. That killed 6 bunnies, with 1 bunny remaining.   And since 1 < 7, that 1 bunny will not be affected by limited food.

**Comment by oliver-phet** [comment] 2020-08-04 16:38
With 1 bunny remaining, the population will always die out, correct? I thought the restriction to not apply limited food if population < 7 was meant to allow the population to stabilize. If 6 of 7 bunnies can still die, then shouldn't the minimum number be increased?

I briefly looked through the default parameters and I see this:
```
limitedFoodPercentToKill: {
    type: 'custom',
    parse: parseRange,
    defaultValue: new Range( 0.6, 0.7 ),
    isValidValue: range => isPercentRange( range )
  },
```
If the maximum (70%) of the population of 7 bunnies die via limited food, 2 should remain?

**Comment by pixelzoom** [comment] 2020-08-04 16:43
The goal is not to guarantee a stable population. The goal is to show that a small population can be sustained on limited food.  That doesn't mean that other factors won't result in the population going to zero.  In this case, your lone bunny will eventually die of old age.

**Comment by pixelzoom** [comment] 2020-08-04 16:53
It is a little curious that you ended up with 1 lone bunny.  If I set up your scenario like this:

1 . Run the sim with query parameters `?brand=phet&initialScreen=2&labMutations=T&labPopulation=1tt,6TT`
2. check the "Limited Food" checkbox
3. Press "Add a Mate" button

... then I see 4 bunnies with long teeth die, and 1 bunny with short teeth dies, leaving me with 2 bunnies.

**Comment by kathy-phet** [comment] 2020-08-04 16:53
Just curious how challenging it is to actually use a tiered death model here, which would be more true to life under limited food, so that there are several tiers and not just jump from none to 2/3 being killed. 
So if say 
>100 bunnies, then 2/3 killed 
100-20 bunnies, then 1/3 killed
20 - 10 bunnies, then 1/4 killed 
<10 none killed
Or something like that.  As it seems pretty aggressive to kill 2/3 with anything over 7 bunnies.

**Comment by pixelzoom** [comment] 2020-08-04 16:59
> Just curious how challenging it is to actually use a tiered death model ...

That will be a rewrite of the food model.  The current model is already pretty complicated, with 6 different parameters that can be tuned (5 query parameters, 1 internal constant).  Adding tiers will obviously make it more complicated and will risk destabilization.  It will take somewhere in the 8-16 hours range, and we'll need to re-tune the model from scratch. If you want to pursue that, I'll be happy to do so.

**Comment by pixelzoom** [comment] 2020-08-04 17:05
Rather than a tiered approach that relies on ranges...  If you can describe the number of bunnies to kill as a function of the total population, that's something that might be dropped into the current model.

**Comment by oliver-phet** [comment] 2020-08-04 17:20
> So I'd be interested if you can describe steps to reproduce what you saw.

It seems to be somehow tied to adding the Long Teeth mutation (note: I'm not turning on Tough Food):
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/5090275/89323959-bcfbe880-d643-11ea-980d-5a7ed390d400.png">
I've only interacted 3 ways (below) but the sim only seems to rarely lead to a situation of 1 bunny (then 0).

1. Add Long Teeth Dominant mutation
2. Check Limited Food
3. Add a bunny

Could it be that 1 bunny dies of old age in addition to 70% of 7 bunnies (5), leaving 1?

**Comment by pixelzoom** [comment] 2020-08-04 17:23
> Could it be that 1 bunny dies of old age in addition to 70% of 7 bunnies (5), leaving 1?

Yes, that's probably the difference in your scenario.  Please add the `log` query parameter, and let me know what's printed to the console.  The log will note how many bunnies have died, and why they died.

**Comment by pixelzoom** [comment] 2020-08-04 17:38
@oliver-phet I'm trying to reproduce what you described in https://github.com/phetsims/natural-selection/issues/153#issuecomment-668722992.

Your steps (as I understand them) are:
1. Start the sim
2. Press the long-teeth dominant button in the Add Mutations panel.
3. Press the "Add a Mate" button
4. Let the sim run

I've now run for 30+ generations, and I've never seen the scenario that you show occurring in generation 15.  What am I doing wrong?  Are you running 1.1.0-dev.2 ?

**Comment by oliver-phet** [comment] 2020-08-04 17:50
I was running from phettest. I had to restart my computer, but I'll try to reproduce with `log`.

**Comment by pixelzoom** [comment] 2020-08-04 17:51
After several attempts running the above steps, I finally duplicated @oliver-phet's scenario.  

Here's are the relevant 2 generations of log messages from the console:

```
====== Generation 21 ======
0 bunnies died of old age
12 dead bunnies pruned
using bunnyRestRange=[2,7] for population=10
8 bunnies were born
attempting to starve bunnies
using bunnyRestRange=[1,3] for population=9
6 bunnies with long teeth died of starvation
3 bunnies with short teeth died of starvation
total live bunnies = 3
total dead bunnies = 173
====== Generation 22 ======
0 bunnies died of old age
12 dead bunnies pruned
4 bunnies were born
attempting to starve bunnies
4 bunnies with long teeth died of starvation
2 bunnies with short teeth died of starvation
total live bunnies = 1
total dead bunnies = 167
```

So generation 22 started with 7 bunnies.  The data probe shows 5 with long teeth, 2 with short teeth.  

4 bunnies with long teeth died.  0.7 * 5 = Math.round( 3.5 ) = 4, so that makes sense.

2 bunnies with short teeth died. 0.7 * 2 = Math.round( 1.4 ) = 1, so that does not make sense.

Investigating...

**Comment by oliver-phet** [comment] 2020-08-04 17:55
Here's another... seems to be the same:
```
[Log] ====== Generation 13 ====== (initialize-globals.js, line 636)
[Log] 0 bunnies died of old age (initialize-globals.js, line 636)
[Log] using bunnyRestRange=[2,7] for population=10 (initialize-globals.js, line 636)
[Log] 8 bunnies were born (initialize-globals.js, line 636)
[Log] attempting to starve bunnies (initialize-globals.js, line 636)
[Log] using bunnyRestRange=[1,3] for population=9 (initialize-globals.js, line 636)
[Log] 6 bunnies with long teeth died of starvation (initialize-globals.js, line 636)
[Log] 3 bunnies with short teeth died of starvation (initialize-globals.js, line 636)
[Log] total live bunnies = 3 (initialize-globals.js, line 636)
[Log] total dead bunnies = 131 (initialize-globals.js, line 636)
[Log] ====== Generation 14 ====== (initialize-globals.js, line 636)
[Log] 0 bunnies died of old age (initialize-globals.js, line 636)
[Log] 4 bunnies were born (initialize-globals.js, line 636)
[Log] attempting to starve bunnies (initialize-globals.js, line 636)
[Log] 4 bunnies with long teeth died of starvation (initialize-globals.js, line 636)
[Log] 2 bunnies with short teeth died of starvation (initialize-globals.js, line 636)
[Log] total live bunnies = 1 (initialize-globals.js, line 636)
[Log] total dead bunnies = 137 (initialize-globals.js, line 636)

```

**Comment by pixelzoom** [comment] 2020-08-04 17:55
Ah, I see the problem.  I'm using `Math.ceil` (which rounds up) instead of `Math.round`.  So for the short-toothed bunnies:

0.7 * 2 = Math.ceil( 1.4 ) = 2

As I recall, I used ` this so that at least 1 bunny would be starved if we got this far in the algorithm.  I'll need to discuss with @amanda-phet.

Thanks for pointing this out @oliver-phet.

**Comment by pixelzoom** [comment] 2020-08-04 18:05
I guess I don't need to discuss with @amanda-phet.

Here's the change to Food.js that will ensure that symmetric rounding is used, but that at least 1 bunny is starved if we get this far in the code:

```diff
- const numberToStarveLongTeeth = Math.ceil( percentToStarveLongTeeth * bunniesLongTeeth.length );
+ const numberToStarveLongTeeth = Math.max( 1, Utils.roundSymmetric( percentToStarveLongTeeth * bunniesLongTeeth.length ) );
- const numberToStarveShortTeeth = Math.ceil( percentToStarveShortTeeth * bunniesShortTeeth.length );
+ const numberToStarveShortTeeth = Math.max( 1, Utils.roundSymmetric( percentToStarveShortTeeth * bunniesShortTeeth.length ) );
```

**Comment by pixelzoom** [comment] 2020-08-04 18:07
There's a similar use of `ceil` in WolfCollection.js (the wolf model) that I'll fix similarly.

**Comment by pixelzoom** [comment] 2020-08-04 18:20
Moving the `ceil` problem to https://github.com/phetsims/natural-selection/issues/155.

**Comment by pixelzoom** [comment] 2020-08-04 18:31
#155 is fixed, so we can proceed with verifying this issue.

**Comment by amanda-phet** [comment] 2020-08-04 19:37
Looks like it is working well to me. I think 7 is a good threshold here. It is reasonable that sometimes the bunnies do die out if they are a very small population, so I wouldn't go any higher than 7. 

@kathy-phet said
>it seems pretty aggressive to kill 2/3 with anything over 7 bunnies.

2/3 is just right to stabilize the population, since every two bunnies will have four babies, so it works pretty well. The percentage killed is randomly selected from within a range (maybe [0.6,0.7], I don't remember exactly) to add some variation, but this does a nice job of stabilizing the population.

**Comment by pixelzoom** [comment] 2020-08-04 20:12
Ready for testing in the next 1.0 (prototype) RC.

**Comment by oliver-phet** [comment] 2020-08-05 22:31
Just to note, it is still possible (but seemingly uncommon) for all of the bunnies to die using the [setup I've been testing](https://github.com/phetsims/natural-selection/issues/153#issuecomment-668722992). It seems to require a small population of bunnies (but above 6), a large portion of them to starve, and a surviving bunny to immediately die of old age.
```
initialize-globals.js:636 ====== Generation 63 ======
initialize-globals.js:636 0 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 using bunnyRestRange=[2,7] for population=10
initialize-globals.js:636 8 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 using bunnyRestRange=[1,3] for population=9
initialize-globals.js:636 8 bunnies with short teeth died of starvation
initialize-globals.js:636 total live bunnies = 4
initialize-globals.js:636 total dead bunnies = 124
initialize-globals.js:636 ====== Generation 64 ======
initialize-globals.js:636 1 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 4 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 5 bunnies with short teeth died of starvation
initialize-globals.js:636 total live bunnies = 2
initialize-globals.js:636 total dead bunnies = 122
initialize-globals.js:636 ====== Generation 65 ======
initialize-globals.js:636 1 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 0 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 limited food is not a factor because population is < 7
initialize-globals.js:636 total live bunnies = 1
initialize-globals.js:636 total dead bunnies = 115
initialize-globals.js:636 ====== Generation 66 ======
initialize-globals.js:636 0 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 0 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 limited food is not a factor because population is < 7
initialize-globals.js:636 total live bunnies = 1
initialize-globals.js:636 total dead bunnies = 107
initialize-globals.js:636 ====== Generation 67 ======
initialize-globals.js:636 0 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 0 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 limited food is not a factor because population is < 7
initialize-globals.js:636 total live bunnies = 1
initialize-globals.js:636 total dead bunnies = 99
initialize-globals.js:636 ====== Generation 68 ======
initialize-globals.js:636 0 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 0 bunnies were born
initialize-globals.js:636 attempting to starve bunnies
initialize-globals.js:636 limited food is not a factor because population is < 7
initialize-globals.js:636 total live bunnies = 1
initialize-globals.js:636 total dead bunnies = 91
initialize-globals.js:636 ====== Generation 69 ======
initialize-globals.js:636 All of the bunnies have died.
initialize-globals.js:636 total live bunnies = 0
initialize-globals.js:636 total dead bunnies = 92
initialize-globals.js:636 1 bunnies died of old age
initialize-globals.js:636 8 dead bunnies pruned
initialize-globals.js:636 0 bunnies were born
```

**Comment by pixelzoom** [comment] 2020-08-05 22:35
As I understand it, @oliver-phet has been testing with `secondsPerGeneration=1` and using the fast-forward button.  That's causing the generation clock to sometimes skip over the food "slice" of the clock, which means bunnies don't starve, which means bunnies can eventually take over the world.  All of these tests are therefore suspect.  First I need to make it impossible to skip the clock slices for food and wolves.  Then we can re-test to see if there's really a problem here.

**Comment by oliver-phet** [comment] 2020-08-05 22:53
I was just able to allow bunnies to take over the world without the fast-forward button with `secondsPerGeneration=1`, but it sounds like even with just `secondsPerGeneration=1`, important steps might be skipped over.

**Comment by pixelzoom** [comment] 2020-08-10 23:35
Since the next RC is going to be published from master, I'm going to go ahead and close this issue.

**Closed by pixelzoom** 2020-08-10 23:35 UTC
Labels: design:general, status:fixed-awaiting-deploy
