### ISSUE TITLE
Minor pointer area inconsistency

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#284] opened 2021-06-28 19:16 UTC
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/662. In published. Very minor and can probably be closed.
The pointer areas around the sunny/snowy scene buttons are slightly different sizes, with sunny being a bit larger. This is the case no matter which one is selected.

**Visuals**
<img width="158" alt="sizeofareas" src="https://user-images.githubusercontent.com/41024075/123691594-0b454780-d813-11eb-9e19-5653ed150748.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html?showPointerAreas
Version: 1.4.0-rc.1 2021-06-21 23:54:30 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2021-06-30 20:22
That's very odd, and a bit concerning since this is handled by common-code RadioButtonGroup.  I'll investigate when I return from vacation.  In the meantime...  @KatieWoe do you see this problem with rectangular radio buttons in any other sims?

**Comment by KatieWoe** [comment] 2021-06-30 20:23
Not that I've noticed, but I also missed this one for a while since the difference was so slight. So I can't make a guarantee. Do what sims I could check to be sure?

**Comment by samreid** [comment] 2021-07-01 17:30
@arouinfar indicated this is not a blocking problem for this release.

**Comment by pixelzoom** [comment] 2021-07-01 17:51
This is a general problem with RectangularRadioButtonGroup, as described in https://github.com/phetsims/sun/issues/708.    The problem is very minor in Natural Selection, and does not affect usability, so we're NOT going to fix it in the 1.4 release.  It will be fixed in master, and picked up in a future release branch (probably 1.5).

Closing as "won't fix".

**Closed by pixelzoom** 2021-07-01 17:51 UTC
Labels: type:bug
