### ISSUE TITLE
Pattern for customization

### ISSUE THREAD

**Issue by samreid** [phetsims/natural-selection#69] opened 2020-05-05 22:40 UTC
@pixelzoom said:

> [P]ropagating flags seems so "spread out".  It would be so much more compact and encapsulated to do something like:

```js
getElement( 'naturalSelection.introScreen.view.addMutationsPanel.earsRow' ).visibleProperty.value = false;
getElement( 'naturalSelection.introScreen.view.addMutationsPanel.teethRow' ).visibleProperty.value = false;
getElement( 'naturalSelection.introScreen.view.environmentalFactorsPanel.limitedFoodCheckbox' ).visibleProperty.value = false;
```

**Comment by samreid** [comment] 2020-05-05 22:45
With these changes:

<details>

```diff

Index: js/common/view/NaturalSelectionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/NaturalSelectionScreenView.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/NaturalSelectionScreenView.js	(date 1588718293662)
@@ -64,11 +64,13 @@
       fixedWidth: rightOfViewportWidth,
       tandem: options.tandem.createTandem( 'addMutationsPanel' )
     } );
+    this.addMutationsPanel = addMutationsPanel;
 
     const environmentalFactorsPanel = new EnvironmentalFactorsPanel( model.environmentModel, {
       fixedWidth: rightOfViewportWidth,
       tandem: options.tandem.createTandem( 'environmentalFactorsPanel' )
     } );
+    this.environmentalFactorsPanel = environmentalFactorsPanel;
 
     const panelsParent = new VBox( {
       children: [ addMutationsPanel, environmentalFactorsPanel ],
Index: js/common/view/EnvironmentalFactorsPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/EnvironmentalFactorsPanel.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/EnvironmentalFactorsPanel.js	(date 1588718330097)
@@ -42,6 +42,9 @@
       tandem: options.tandem.createTandem( 'titleNode' )
     } );
 
+    const limitedFoodCheckbox = new LimitedFoodCheckbox( environmentModel.foodSupply.isLimitedProperty, {
+      tandem: options.tandem.createTandem( 'limitedFoodCheckbox' )
+    } );
     const checkboxes = new VBox( merge( {}, NaturalSelectionConstants.VBOX_OPTIONS, {
       children: [
 
@@ -56,18 +59,19 @@
         } ),
 
         // Limited Food
-        new LimitedFoodCheckbox( environmentModel.foodSupply.isLimitedProperty, {
-          tandem: options.tandem.createTandem( 'limitedFoodCheckbox' )
-        } )
+        limitedFoodCheckbox
       ]
     } ) );
 
+
     const content = new VBox( merge( {}, NaturalSelectionConstants.VBOX_OPTIONS, {
       children: [ titleNode, checkboxes ]
     } ) );
 
     super( content, options );
 
+    this.limitedFoodCheckbox = limitedFoodCheckbox;
+
     // Set the panel's title to singular or plural, depending on how many checkboxes are visible.
     checkboxes.boundsProperty.link( () => {
       const visibleCount = _.filter( checkboxes.children, child => child.visible ).length;
Index: js/common/view/AddMutationsPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/AddMutationsPanel.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/AddMutationsPanel.js	(date 1588718269364)
@@ -96,6 +96,7 @@
     const earsRow = new Row( genePool.earsGene, iconsAlignGroup, labelColumnAlignGroup, buttonColumnsAlignGroup, {
         tandem: options.tandem.createTandem( 'earsRow' )
       } );
+
     const teethRow = new Row( genePool.teethGene, iconsAlignGroup, labelColumnAlignGroup, buttonColumnsAlignGroup, {
         tandem: options.tandem.createTandem( 'teethRow' )
       } );
@@ -119,7 +120,7 @@
 
     super( content, options );
 
-    // @private
+    // @public (for customization)
     this.furRow = furRow;
     this.earsRow = earsRow;
     this.teethRow = teethRow;

```

</details>

These lines can be added to the end of the IntroScreenView constructor:

```js
this.addMutationsPanel.earsRow.visibleProperty.value = false;
this.addMutationsPanel.teethRow.visibleProperty.value = false;
this.environmentalFactorsPanel.limitedFoodCheckbox.visibleProperty.value = false;
```

**Comment by pixelzoom** [comment] 2020-05-05 23:31
Duplicate of #70.  I'm going to close this issue, since #70 contains more detail.

**Closed by pixelzoom** 2020-05-05 23:31 UTC
