### ISSUE TITLE
Reset all not resetting everything properly after generation 17

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#125] opened 2020-07-09 23:45 UTC
Using https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.66/phet/natural-selection_en_phet.html?wolvesPercentToKill=.35,.4&wolvesEnvironmentMultiplier=2.3&limitedFoodPercentToKill=.6,.7&toughFoodPercentToKill=.4,.7&shortTeethMultiplier=1.4&limitedFoodMultiplier=1.02&ae&minBunniesForFood=3 

Mac OS 10.15, Chrome. 

Issue: clicking reset-all doesn't fully reset the sim. 
![image](https://user-images.githubusercontent.com/7852916/87101258-da3bc380-c20b-11ea-9880-d10d8f79f057.png)

Bunnies had not taken over or died. I can try to dive deeper into understand the bug if that's helpful.

**Comment by pixelzoom** [comment] 2020-07-10 00:11
Any console output?

**Comment by pixelzoom** [comment] 2020-07-10 00:12
I see that you're just past generation 16.  This is probably the same problem as https://github.com/phetsims/natural-selection/issues/120, a bug in pruning.   I can't reproduce because I haven't discovered the magic to make the sim run that long, see #119.

**Comment by amanda-phet** [comment] 2020-07-10 01:36
>I see that you're just past generation 16. This is probably the same problem as #120, a bug in pruning.

I believe you are correct. 

When I click reset, I see the following:

Assertion failed: reentry detected, value=0, oldValue=172.7019999999991
assert.js:22 Uncaught Error: Assertion failed: reentry detected, value=0, oldValue=172.7019999999991
    at window.assertions.assertFunction (assert.js:22)
    at NumberProperty._notifyListeners (Property.js:270)
    at NumberProperty.set (Property.js:171)
    at NumberProperty.reset (Property.js:336)
    at NumberProperty.reset (NumberProperty.js:175)
    at GenerationClock.reset (GenerationClock.js:91)
    at LabModel.startOver (NaturalSelectionModel.js:226)
    at LabModel.reset (NaturalSelectionModel.js:210)
    at listener (NaturalSelectionScreenView.js:181)
    at ResetAllButton.options.listener (ResetAllButton.js:62)

![image](https://user-images.githubusercontent.com/7852916/87106761-643f5880-c21b-11ea-8c44-178fda1da9b8.png)


Feel free to close this if it is a pure duplicate of #120.

**Comment by pixelzoom** [comment] 2020-07-13 19:08
Moving this to https://github.com/phetsims/natural-selection/issues/127.

**Closed by pixelzoom** 2020-07-13 19:08 UTC
Labels: type:bug
