### ISSUE TITLE
Playback wrapper has strange shaking

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/natural-selection#238] opened 2020-09-23 00:50 UTC
<b>Test Device</b>

Windows 10 Laptop

<b>Operating System</b>

Windows 10 2004

<b>Browser</b>

Chrome  85.0.4183.102

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/551

Found in the playback of a recording made with the record wrapper. There seems to be a strange shaking while only seen in playback. Possibly a result of my device.

<b>Visuals</b>

![2020-09-22NSLogShakes](https://user-images.githubusercontent.com/54685448/93951627-17d8c480-fd04-11ea-99d4-2cd7ee2d6f7e.gif)

**Comment by pixelzoom** [comment] 2020-09-23 02:14
@KatieWoe  You previously reported that the shrubs were flickering on playback in https://github.com/phetsims/natural-selection/issues/226.  (That issue was deferred by @ariel-phet.) Are the visuals similar here?

**Comment by KatieWoe** [comment] 2020-09-23 14:40
This is the same issue. It can probably be marked duplicate and closed.

**Comment by pixelzoom** [comment] 2020-09-23 15:21
Closing as a duplicate of #226.  Thanks for reporting @loganbraywork!

**Closed by pixelzoom** 2020-09-23 15:21 UTC
Labels: dev:phet-io, type:bug
