### ISSUE TITLE
Flickering bushes (shrubs) on playback

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#226] opened 2020-09-11 15:54 UTC
Found during testing for https://github.com/phetsims/phet-io/issues/1654. Win 10 Firefox. Both recording and playback on master.
While recording the sim behaved normally. However, during playback the bushes in the play area started flickering. The tough bushes showed this a bit better.
![flickerbush](https://user-images.githubusercontent.com/41024075/92947000-a865f980-f414-11ea-9243-e54916f1fa63.gif)

**Comment by pixelzoom** [comment] 2020-09-11 16:29
I'm not familiar with record & playback, and I have no idea why just the bushes might flicker on playback.  Maybe it's noticeable because there are a large number of them.

@KatieWoe could you please try a playback scenario that has a large number of bunnies (white and brown) to see if there's any noticeable flicker in the bunnies when there are more of them?

**Comment by pixelzoom** [comment] 2020-09-11 16:32
Assigning to @amanda-phet to make the call on where this blocks publication for the 10/1 deliverable. Labeling as "block-sim-publication" until we determine otherwise.

**Comment by KatieWoe** [comment] 2020-09-11 16:48
Still happens when there are a large number of bunnies. But I didn't see the bunnies flashing themselves.

**Comment by amanda-phet** [comment] 2020-09-15 02:34
@ariel-phet ? 

I am wondering if something similar has happened with other sims. I have no idea how often playback is tested. 

My inclination is to defer this until a client tells us they want it changed.

**Comment by KatieWoe** [comment] 2020-09-15 14:39
It's generally tested whenever phet-io is tested.

**Comment by pixelzoom** [comment] 2020-09-15 17:17
@KatieWoe can you please described the test procedure, or point me to where it's described? I'm not familiar with record/playback and I'd like to be able to reproduce this.

**Comment by samreid** [comment] 2020-09-15 17:20
Launch the "recording" wrapper with ?localFile, like

http://localhost/main/phet-io-wrappers/record/?sim=natural-selection&localFile&phetioDebug

Then play with the sim for a bit, then type `window.saveLogToFile('myfile.log');` in the console.

Then open the playback wrapper, then select myfile.log and press play.

**Comment by ariel-phet** [comment] 2020-09-15 19:05
Most definitely not blocking. In fact, I am going to mark deferred. This is a minor aesthetic issue  in my opinion and should not currently be addressed. It is unclear to me why a client would care if the focus is on understanding a student use.

**Comment by pixelzoom** [comment] 2020-09-27 14:56
@ariel-phet deferred this issue in https://github.com/phetsims/natural-selection/issues/226#issuecomment-692917761.   Please clarify whether this should be addressed for the 1.3 release, or is something that we don't intended to address.  If the latter, please close this issue.

**Comment by ariel-phet** [comment] 2020-09-30 05:06
@pixelzoom I think we should investigate a bit. I definitely do not think we need to address this this issue for 1.3, but it would be worthy of a couple hours of investigation just to understand the root cause (and if it is a general issue or quite sim specific). Once we understand the cause and if it would be easy or complex to fix we can make a further call.

**Comment by pixelzoom** [comment] 2020-10-01 23:13
I spend ~15 minutes on this, then hit a wall.  I reproduced the flickering with NS unbuilt + macOS 10.15.6 + Chrome) reproducing, following the steps in https://github.com/phetsims/natural-selection/issues/226#issuecomment-692856874.  Then I poked around a little in scenery and the wrappers, but they are outside of my knowledge base. I have no idea why this only occurs in the Playback wrapper, or where to even begin investigating. 

Back to @ariel-phet for assignment and prioritization. You'll probably need to involve @jonathanolson, and maybe someone from the iO team who is the Playback wrapper expert.

**Comment by ariel-phet** [comment] 2020-10-05 16:48
Not worth pursuing currently. Marking as `wontfix` -- we can reopen if there is a client need

**Closed** 2020-10-05 16:48 UTC
Labels: phet-io:record-and-playback, type:bug, type:wontfix

**Comment by KatieWoe** [comment] 2021-04-05 22:58
Noting this in https://github.com/phetsims/QA/issues/636 but not reoppening since this was marked as wont-fix

**Comment by kathy-phet** [comment] 2021-04-12 17:28
Yes, still wontfix.
