### ISSUE TITLE
CT: countProperty should match array length

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#117] opened 2020-07-09 14:58 UTC
Seems similar to https://github.com/phetsims/natural-selection/issues/89
```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594253492079%22%2C%22timestamp%22%3A1594276335902%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/tandem/js/PhetioGroup.js:69:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/axon/js/Emitter.js:58:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/phet-io/js/PhetioStateEngine.js:254:26)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/phet-io/js/phetioCommandProcessor.js:268:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594253492079/phet-io/js/phetioCommandProcessor.js:160:36
id: Bayes Chrome
Snapshot from 7/8/2020, 6:11:32 PM
```

**Comment by pixelzoom** [comment] 2020-07-09 15:56
This problem started at 5:49pm yesterday (7/8/20) and has been occurring intermittently since.  There have been no changes related to PhetioGroup in the sim for many days.  Might this be related to some PhET-iO common-code change?

**Comment by pixelzoom** [comment] 2020-07-09 16:02
Chris Malley  9:56 AM
Have there been any recent changes that might affect PhetioGroup's countProperty? See https://github.com/phetsims/natural-selection/issues/117

Sam Reid:house_with_garden:  10:00 AM
Not purposefully and none I am aware of.  Also, you should know you can click on the column headers in CT to see a list of changed SHAs

Michael Kauzmann  10:01 AM
I haven't touched it since making that property and causing many bugs that you were a part of a some weeks ago.

**Comment by pixelzoom** [comment] 2020-07-09 16:06
This is the assertion that's failing in PhetioGroup:

```js
    // countProperty can be overwritten during state set, see PhetioGroup.createIndexedELement(), and so this assertion
    // makes sure that the final length of the elements array matches the expected count from the state.
    assert && Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( state => {

      // This supports cases when only partial state is being set
      if ( state[ this.countProperty.tandem.phetioID ] ) {
        assert( state[ this.countProperty.tandem.phetioID ].value === this._array.length, 'countProperty should match array length.' );
      }
    } );
```

**Comment by pixelzoom** [comment] 2020-07-09 16:11
Re: `Uncaught RangeError: Maximum call stack size exceeded` ....

This smells like an infinite loop.

**Comment by zepumph** [comment] 2020-07-09 17:02
>This problem started at 5:49pm yesterday (7/8/20) and has been occurring intermittently since. There have been no changes related to PhetioGroup in the sim for many days. Might this be related to some PhET-iO common-code change?


The last time we encountered this error, it had to do with the potential for Property listeners, or other logic that executes because of the PhET-iO state being set, changing the number of dynamic elements in a sim. For example, when setting a state, the PhetioGroup will create 6 bunnies, and it will change some theoritical Property called `happinessProperty`. If happinessProperty has a listener that says "if happiness was high and is now low, kill a bunny" that shouldn't happen during state setting. This is because that listener has already a bunny to be killed in the "source" frame. 

From this explanation, I would take a look at any code you committed yesterday that may have manipulated a dynamic element (add or remove) downstream of a stateful and instrumented PhetioObject (probably a Property listener).

**Comment by pixelzoom** [comment] 2020-07-09 17:59
Hmm... I'm unable to reproduce locally with `phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz`.  And CT has now been error-free for 5 cycles.

**Comment by pixelzoom** [comment] 2020-07-09 22:08
Very odd, this has not reoccured in CT for 13 cycles.  The only thing that I changed was #118, which should have been unrelated.

**Comment by pixelzoom** [comment] 2020-07-13 16:54
This finally occurred again (once) 7/11/2020, 11:04:32 PM.

**Comment by pixelzoom** [comment] 2020-07-14 20:07
Happened again at 7/14/2020, 10:57:15 AM.   This is occurring infrequently/inconsistently, so it's likely a case that's difficult to reach in the State Wrapper using CT.

**Comment by pixelzoom** [comment] 2020-07-14 20:46
In https://github.com/phetsims/natural-selection/issues/117#issuecomment-656243154, @zepumph said:
> ... From this explanation, I would take a look at any code you committed yesterday that may have manipulated a dynamic element (add or remove) downstream of a stateful and instrumented PhetioObject (probably a Property listener).

I have been unable to identify such a code change.

**Comment by pixelzoom** [comment] 2020-07-22 16:21
There's a new issue (#138) for test "phet-io-state-fuzz : unbuilt".  But this one has self-healed. It was probably related to working out general bugs in the new sprites implementation.  Closing.

**Comment by pixelzoom** [comment] 2020-08-03 20:51
Reopening. This is still a problem.

Steps to reproduce:
1. Start the sim in State Wrapper with `?sim=natural-selection&phetioValidateTandems&phetioDebug`
2. Go to Intro screen
3. Check the "Wolves" checkbox
4. Press "Add a Mate" button
5. Let the sim run and wait for the assertion failure to occur when the wolves appear

```
Assertion failed: countProperty should match array length.
?sim=natural-selection&phetioValidateTandems&phetioDebug:115 Uncaught Error: Assertion failed: countProperty should match array length.
    at window.assertions.assertFunction (assert.js:22)
    at PhetioGroup.js:69
    at TinyEmitter.emit (TinyEmitter.js:69)
    at Emitter.js:33
    at Emitter.execute (Action.js:225)
    at Emitter.emit (Emitter.js:58)
    at PhetioStateEngine.setState (PhetioStateEngine.js:250)
    at PhetioStateEngine.setFullState (PhetioStateEngine.js:264)
    at PhetioEngineIO.implementation (PhetioEngineIO.js:221)
    at PhetioCommandProcessor.processCommand (phetioCommandProcessor.js:276)
createError @ Client.js:1547
createErrors @ Client.js:1564
errorListenerFunction @ Client.js:860
dispatch @ Client.js:485
windowMessageListener @ Client.js:348
postMessage (async)
send @ phetioCommandProcessor.js:303
processCommands @ phetioCommandProcessor.js:173
(anonymous) @ phetioCommandProcessor.js:100
postMessage (async)
invokeSequence @ Client.js:630
invoke @ Client.js:554
(anonymous) @ ?sim=natural-selection&phetioValidateTandems&phetioDebug:141
dispatch @ Client.js:519
windowMessageListener @ Client.js:348
postMessage (async)
send @ phetioCommandProcessor.js:303
processCommands @ phetioCommandProcessor.js:173
(anonymous) @ phetioCommandProcessor.js:100
postMessage (async)
invokeSequence @ Client.js:630
invoke @ Client.js:554
update @ ?sim=natural-selection&phetioValidateTandems&phetioDebug:133
setInterval (async)
(anonymous) @ ?sim=natural-selection&phetioValidateTandems&phetioDebug:163
simInitializedListenerFunction @ Client.js:781
dispatch @ Client.js:485
windowMessageListener @ Client.js:348
postMessage (async)
send @ phetioCommandProcessor.js:303
triggerSimInitialized @ phetioCommandProcessor.js:147
(anonymous) @ phetioEngine.js:152
callback @ timer.js:39
emit @ TinyEmitter.js:69
(anonymous) @ Sim.js:282
execute @ Action.js:225
stepSimulation @ Sim.js:952
stepOneFrame @ Sim.js:942
runAnimationLoop @ Sim.js:925
(anonymous) @ Sim.js:864
setTimeout (async)
(anonymous) @ Sim.js:842
setTimeout (async)
runItem @ Sim.js:824
(anonymous) @ Sim.js:839
setTimeout (async)
runItem @ Sim.js:824
(anonymous) @ Sim.js:839
setTimeout (async)
runItem @ Sim.js:824
(anonymous) @ Sim.js:839
setTimeout (async)
runItem @ Sim.js:824
(anonymous) @ Sim.js:839
setTimeout (async)
runItem @ Sim.js:824
(anonymous) @ Sim.js:839
setTimeout (async)
runItem @ Sim.js:824
start @ Sim.js:905
(anonymous) @ natural-selection-main.js:50
window.phet.joist.launchSimulation @ simLauncher.js:91
implementation @ PhetioEngineIO.js:293
processCommand @ phetioCommandProcessor.js:276
(anonymous) @ phetioCommandProcessor.js:163
processCommands @ phetioCommandProcessor.js:161
(anonymous) @ phetioCommandProcessor.js:100
postMessage (async)
invokeSequence @ Client.js:630
invoke @ Client.js:554
(anonymous) @ ?sim=natural-selection&phetioValidateTandems&phetioDebug:224
phetioInitializedListenerFunction @ Client.js:818
dispatch @ Client.js:485
windowMessageListener @ Client.js:348
postMessage (async)
send @ phetioCommandProcessor.js:303
initializeCrossFrameMessaging @ phetioCommandProcessor.js:133
initialize @ phetioEngine.js:111
proceedIfReady @ simLauncher.js:96
(anonymous) @ simLauncher.js:132
load (async)
(anonymous) @ logo_png.js:5
assert.js:21 Assertion failed: cannot set state while setting state
```

I particularly enjoy the last assertion message, "cannot set state while setting state". 

Putting a `debugger` statement in assert.js doesn't provide a more useful stack trace in this case.

I'm guessing there's some problem with PhetioGroup's countProperty, but no idea how to debug this. Assigning to the PhET-iO team for assistance.

**Comment by samreid** [comment] 2020-08-04 01:28
I was able to reproduce the problem following the instructions in the preceding comment.  I recommend increasing priority for this issue.

**Comment by samreid** [comment] 2020-08-04 19:10
@chrisklus and I proposed a solution in the commit, @pixelzoom can you please review?

**Comment by pixelzoom** [comment] 2020-08-04 19:19
Thanks, that commit looks like it will do the job.  I probably can ignore cherry-pick to the 1.0 (prototype) branch, but let me think that over.

Two things...

(1) I must reiterate that I really<sup>100</sup> dislike this approach of creating different code paths based on `phet.joist.sim.isSettingPhetioStateProperty.value`.  And in the absence of a better way, that approach keeps proliferating.  But I guess that's what I'll need to do for now.

(2) This problem was reported 7/9 by CT, and then disappeared from CT. Then I stumbled across it on 8/3 while running the State Wrapper.  Clearly our tooling doesn't have an adequate way of automatically identifying this very-common type of problem.

**Comment by pixelzoom** [comment] 2020-08-04 19:32
(3) When a State Wrapped problem does occur, it's not clear (to me) how to go about identifying the source of the problem. Having to put a `debugger` statement in assert.js is inconvenient and (as in this case) doesn't always yield results.   How did you go about debugging this? Should that process be described somewhere? Can/should that process be improved since this is a common problem?

**Comment by chrisklus** [comment] 2020-08-04 19:40
> (1) I must reiterate that I really<sup>100</sup> dislike this approach of creating different code paths based on `phet.joist.sim.isSettingPhetioStateProperty.value`.  And in the absence of a better way, that approach keeps proliferating.  But I guess that's what I'll need to do for now.

We say the same thing every day!

> (2) This problem was reported 7/9 by CT, and then disappeared from CT. Then I stumbled across it on 8/3 while running the State Wrapper.  Clearly our tooling doesn't have an adequate way of automatically identifying this very-common type of problem.

We were thinking this was more related to the nature of our fuzz tests and how they often don't catch scenarios that take time to get to before the reset button is hit again. In this case, 5 seconds needs to pass before another generation is created. @samreid and I commented out our fix and the ResetAllButtons and hit the error on our first try of running the state wrapper. Perhaps CT could be improved by adding sim tests without ResetButtons or disabling the reset buttons for intermittent parts of the test.

>(3) When a State Wrapped problem does occur, it's not clear (to me) how to go about identifying the source of the problem. Having to put a `debugger` statement in assert.js is inconvenient and (as in this case) doesn't always yield results.   How did you go about debugging this? Should that process be described somewhere? Can/should that process be improved since this is a common problem?

Checking "Pause on caught exceptions" is a nice alternative to putting a `debugger` statement in assert.js. To have dev tools open on page load with this checked, you'll likely need to blackbox some scripts so those aren't paused first. @samreid and I added at least jquery and isHMR. In this case, we noticed that too many wolves were being created, so we put a debugger when the unexpected wolf was being created, and that helped us trace it back to `isHuntingProperty`.

**Comment by pixelzoom** [comment] 2020-08-04 20:45
Thanks for the replies.

I did decide to cherry-pick this for the 1.0 (prototype) branch, since there have been other changes to WolfCollection.js, and I want to make cherry-picking easy going forward. 

Ready for review in the next RC.  There is nothing specific to test, just be on the lookout for any errors when Wolves are enabled.

**Comment by pixelzoom** [comment] 2020-08-06 15:28
Since the next 1.0 RC is going to be a merge from master, closing this issue.

**Closed by pixelzoom** 2020-08-06 15:28 UTC
Labels: dev:phet-io, status:fixed-awaiting-deploy, type:automated-testing
