### ISSUE TITLE
Migrate type-checking utils to common?

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/natural-selection#96] opened 2020-06-02 04:43 UTC
Over in `CollisionLabUtils`, I have copied and pasted `assertPropertyTypeof` and `assertPropertyInstanceOf` from `NaturalSelectionUtils`. I've also copied a variant of `isArrayOf` from `GasPropertiesUtils`. 

I've found all of these useful in my type-checking assertions and I'm wondering if it would be beneficial to migrate to common. Maybe expanding PhETs assertions module or making a class called something like `AssertTypes`. You also have in the doc "//TODO should any of these be migrated to common?".

**Comment by pixelzoom** [comment] 2020-06-02 15:29
Glad you find these useful.  Adding a collection of useful assertions to common code sounds great to me. Gas Properties was the first sim where I went "all in" on type-checking method arguments, and I feel like it's been a valuable addition to my JavaScript programming style.

Note that phet-core has assertHasProperties.js and assertMutuallyExclusiveOptions.js, which are additional assertion "utility" functions.  They are not related to type checking per se.  I haven't used these, but we should consult the authors (@samreid @zepumph) to see if they should be added to a collection of "useful assertions", or whether they should remain in their own files.

If we put this in the assert repo, we'll have to be careful not to introduce dependencies on any other repos.  If we want to have something like your `CollisionLabUtils.consistsOf`, then we will need to import `ObservableArray` and therefore have a dependency on axon.

As for name...  Here are a few ideas, including your `AssertTypes` suggestion:
 
```js
assert && AssertTypes.assertPropertyTypeof( isPlayingProperty, 'boolean' );
assert && AssertUtils.assertPropertyTypeof( isPlayingProperty, 'boolean' );
assert && TypeChecks.assertPropertyTypeof( isPlayingProperty, 'boolean' );
```

If we pull in the functions from phet-core, I'd lean towards `AssertUtils`, since the collection would not be limited to type-checking.

Thoughts?

**Comment by samreid** [comment] 2020-06-02 15:40
How about an API that lets us check all of the arguments at once?  For instance, BunnyGroup currently is coded like so:

```js
  constructor( genePool, modelViewTransform, options ) {

    assert && assert( genePool instanceof GenePool, 'invalid genePool' );
    assert && assert( modelViewTransform instanceof EnvironmentModelViewTransform, 'invalid modelViewTransform' );

```

If we define `assertTypes` appropriately, we could have the API read like so:

```js
  constructor( genePool, modelViewTransform, options ) {

    assert && assertTypes( arguments, GenePool, EnvironmentModelViewTransform, Options );
```

**Comment by pixelzoom** [comment] 2020-06-02 15:43
That looks like over-generalization to me.  How does that API support checking that that an argument is a Property with a specific type of value? Or a homogenous array with elements of a specific type? Or supporting optional assertion message that might be needed to provide the bad value or other context?

**Comment by pixelzoom** [comment] 2020-06-02 15:46
Looks to me like phetcommon might be the appropriate repo for this collection.  It already has a dependency on axon.  Maybe phetcommon/util/AssertUtils.js ?

**Comment by brandonLi8** [comment] 2020-06-02 15:50
> If we pull in the functions from phet-core, I'd lean towards AssertUtil

I concur. My vote would also be to move `assertHasProperties.js` and `assertMutuallyExclusiveOptions.js` into `AssertUtil`.

**Comment by samreid** [comment] 2020-06-02 17:00
> How does that API support checking that an argument is a Property with a specific type of value? Or a homogenous array with elements of a specific type?

Could we use a pattern like PhET-iO for this?

```js
assert && assertTypes( arguments, PropertyIO(NumberIO), StringIO)
```

> Or support for an optional assertion message that might be needed to provide the bad value or other context?

By default, `assertTypes` could report (a) the expected type, (b) the actual type and (c) the actual instance and (d) the index where the bad element appeared.  This could be "factored out" so it isn't duplicated across each checks if they are done separately.  If something more complex is needed for a single element, it could be checked with a custom one-parameter check, in addition to the overall default `assertTypes` check.

Also inviting @zepumph based on his work in `ValidatorDef`.

**Comment by pixelzoom** [comment] 2020-06-02 22:07
@brandonLi8 FYI... As an intermediate step, I've moved all of the natural-selection assertion methods to natural-selection/AssertUtils.js.

**Comment by zepumph** [comment] 2020-06-03 18:41
I feel like this is a very nice collection of functions. If it is useful NS and CL, then likely it will be useful elsewhere. I thoughts are mainly to try to limit duplicated code.

I think the whole thing should be rewritten with `validate`, in which `ValidatorDef` can be passed in/created/or mutated (if there are memory worries). This is a standard that axon has moved to, and I think makes sense in this case to. For example this is one way (of many) that  `assertPropertyPredicate` could be written with this format.
```js
  assertPropertyPredicate( object, validator ) {
    validate( object, { valueType: Property } );
    validate( object.value, validator );
  },

// and for assertRangeInclusive
  assertRangeInclusive( range, min, max ) {
    validate( range, { valueType: Range, isValidValue: range => range.min >= min && range.max <= max } );
  },
```


As for @samreid's thoughts about assertTypes with IO types, it makes me feel like we are burning the validation candle heavily from both ends. We have already implemented all of this logic to be passed to a Property to validate its own value. It feels like a bummer to build out a fully separate API for validating parameters. Just brainstorming. . . perhaps there is a way of asserting that Properties have appropriate `validatorDef` keys, instead of duplicating that when declaring the Property and when passing it to a constructor for use. I'm not sure I agree with that sentiment though because a Type's constructor should just validate based on its needs, which could be a subset or superset (depending on case) of the Property's built in validation. 

-----------------

These functions match very closely the idea for "next steps" when creating `ValidatorDef.js`, in which we can determine the validation needs that continue to happen frequently, and factor them out to a central location. One place I could see this happening is in a new type called `ValidatorUtils` or `Validation`. In lieu of this, I added a common function to validate.js itself. Not sure which is better. What do people think?

**Comment by samreid** [comment] 2020-06-03 20:04
How about combining the idea about validating all the arguments with the idea about using `ValidatorDef`?  Call site could look like:

```js
assert && assertAllValid( arguments, {valueType: 'number'}, { valueType: MyEnumeration } );
```

**Comment by pixelzoom** [comment] 2020-06-04 17:08
> `I think the whole thing should be rewritten with `validate`

I considered this when writing the assertions. But I see no additional value added by using `validate`.  For example:
```
  // Current implementation:
  assertRangeInclusive( range, min, max ) {
    assert && assert( range instanceof Range, 'invalid range' );
    assert && assert( range.min >= min && range.max <= max, `invalid range: ${range}` );
  },

  // Proposed change:
  assertRangeInclusive( range, min, max ) {
    validate( range, { valueType: Range, isValidValue: range => range.min >= min && range.max <= max } );
  },
```

Not only is using `validate` no less verbose, it does not support a specific assertion message.

> How about combining the idea about validating all the arguments with the idea about using ValidatorDef? 

I am not at all interested in combining all arguments into one assertion. It's too verbose. How do I add messages that are parameter-specific?  Why must I verify _every_ argument? - that's not a goal. 

I'm not sure how to proceed here.  I have some very simple, useful assertions that allow me to type-check specific arguments (not _all_ arguments), and make my programming more robust.  @brandonLi8 wants to reuse them.   I would like to keep them simple, and the suggestions so far move this in a more complicated direction.

I'd also like to know - @samreid @zepumph do you plan to use these assertion utilities in your code? I see very sparse evidence of argument type-checking in the sims that you're responsible for.

**Comment by pixelzoom** [comment] 2020-06-04 18:17
I decided to move forward with migrating AssertUtils.js without radically changing its API or implementation.  In the above commits, I have:

* generalized and migrated AssertUtil.js to phetcommon
* used AssertUtil.js in natural-selection and collision-lab
* removed duplicate code from CollisionLabUtils.js

@brandonLi8 please review the changes to collision-lab, and have a look through Assert.js.

**Comment by brandonLi8** [comment] 2020-06-04 18:20
@pixelzoom Thanks for doing this and updating collision-lab!

It looks like you registered `AssertUtils` to the wrong namespace: ie.
`naturalSelection.register( 'AssertUtils', AssertUtils );`. Other than that, the api looks good to me and works in collision lab.

**Comment by pixelzoom** [comment] 2020-06-04 18:22
Good catch! Namespace fixed in the above commit.

**Comment by pixelzoom** [comment] 2020-06-04 19:29
@brandonLi8 @samreid @zepumph any feelings on how to proceed?  Whether to do anything else here? I'm happy with AssertUtils.js in its current state.

**Comment by brandonLi8** [comment] 2020-06-04 22:22
>  I'm happy with AssertUtils.js in its current state.
+1 from me.

I also haven't used `assertHasProperties.js `and `assertMutuallyExclusiveOptions.js`, but I think its probably good to unify a location for assert related stuff in AssertUtils.js.

**Comment by pixelzoom** [comment] 2020-06-04 23:23
Assuming that the authors are OK with moving them to AssertUtils.js...

There are 6 occurrences of `import assertHasProperties`, all in common code: 5 in sun, 1 in scenery. The 1 is scenery (Paintable) is problematic.  I don't think that scenery is supposed to have dependencies on phetcommon. So we'd have to relocate AssertUtils.js - but where?

There are 4 occurrences of  `import assertMutuallyExclusiveOptions`, all in common code: 1 in axon, 2 in sun, 1 in tandem.

**Comment by zepumph** [comment] 2020-06-05 00:15
I am ambivalent  about moving these into the common type. I think it makes sense organizationally, but I remember a conversation at one point where @jonathanolson said he wished that DOT/Utils.js was just a bunch of individual functions. No strong preference here.

Also note that if you want to use these in scenery, phet-core is the repo for you!

**Comment by pixelzoom** [comment] 2020-06-05 00:30
Can phet-core have dependencies on axon? I thought not, which is why AssertUtils.js currently lives in phetcommon.    See previous pondering in https://github.com/phetsims/natural-selection/issues/96#issuecomment-637621857 and https://github.com/phetsims/natural-selection/issues/96#issuecomment-637638000.

**Comment by zepumph** [comment] 2020-06-05 00:36
It seems a bit arbitrary that phetcommon has a dependency on axon and phet-core doesn't. Also note that mergeTests imports Property, and perhaps we should break that dependency. 

I don't really care where we go from even, even if that means keeping things as is. I also don't want us to think that phetcommon is meant to have an axon dependency whereas phet-core is not. Or at least I don't see that in the docs.

**Comment by samreid** [comment] 2020-06-05 06:03
I think it would be safe to have phet-core import `axon/Property` for this usage. Projects like scenery that depend on phet-core also already depend on axon. But have you considered putting `AssertUtils.js` in the `assert` repo?

**Comment by pixelzoom** [comment] 2020-06-05 13:37
> But have you considered putting `AssertUtils.js` in the `assert` repo?

That was the first place I considered. But making the assert repo dependent on axon seemed wrong.

> Have you considered putting the type-specific assertions with their corresponding types?  ... You can see that the proposed pattern is non-scalable by doing a thought experiment ...

I get it.  It would probably take me another 30 minutes to do that.  And it's not clear where `assertHasProperties`, `assertMutuallyExclusiveOptions`, and future assertions that are not type-specific would live. 

But I'm skeptical that this needs to be scalable, because:

(1) This set of functions was intended for type-checking, not for providing a way of validating any instance of any type.  And (doing the thought experiment) I don't see myself taking type-checking so far that I need something like `assertSliderTickMarkValid`.

(2) This collection was supposed to be simple, to eliminate a small amount of code duplication. The more complicated it gets, the less valuable it is to me. I already feel like I've put a disproportionate amount of energy into generalizing, and the benefit that I've gotten is quickly being erased.

(3) As far as I can tell, no one (other than Brandon) has expressed an interest in doing argument type-checking to the extent that I'm doing it. I certainly don't see evidence of rigorous type-checking in anyone else's code. And maybe I'm wrong, but I doubt that my approach is something that PhET developers would adopt as a convention. It's more likely (and imo more appropriate) that PhET would move to TypeScript.  So I'm not interested in trying to convert other developers to this approach - this approach works for me, it doesn't have to work for everyone else.

So... I appreciate all of the input and brainstorming, and I feel like this has been a useful discussion.  But the last task that I'm going to do here is to decide whether AssertUtils.js belongs in a more appropriate repo.  If someone feels strongly that there's more to do here, please add the "meeting:developer" label for further discussion. I'll be happy to participate in more generalization if the PhET development team agrees that using assertions in this way should be a PhET convention, and that it's worth the cost.

**Comment by jonathanolson** [comment] 2020-06-05 14:24
> As far as I can tell, no one (other than Brandon) has expressed an interest in doing argument type-checking to the extent that I'm doing it. I certainly don't see evidence of rigorous type-checking in anyone else's code.

I prefer more type checks, and will probably add more once I adjust my Sublime plugin to auto-add type checks based on function parameter JSDoc.

> Can phet-core have dependencies on axon?

Ideally, to me, phet-core is a fairly "root" repository that doesn't depend on things, but we haven't maintained strict separation. phet-core currently has dependencies (in imports) on axon, tandem, dot, and scenery (!)

We've seemed to consider things more of a single repository for a lot of common code, and while I don't expect issues from the above, it's definitely caused problems in general (e.g. CT's report interface needs to run initialize-globals as if it's a sim, and includes a fake `window.phet.chipper.packageObject`...).

I'll probably create an issue to discuss separately.

**Comment by pixelzoom** [comment] 2020-06-05 14:51
@jonathanolson Thanks for the input. Do you think we should leave AssertUtil.js in phetcommon for now, or move it to phet-core? (or somewhere else?)

**Comment by jonathanolson** [comment] 2020-06-09 17:34
> @jonathanolson Thanks for the input. Do you think we should leave AssertUtil.js in phetcommon for now, or move it to phet-core? (or somewhere else?)

phetcommon seems good to me.

> I don't see any issue. Did you create one, or forget to mention this one?

I decided to not create an issue.

**Comment by pixelzoom** [comment] 2020-06-09 22:15
OK, I'm going to leave it in phetcommon, and close this issue.

If someone feels strongly that there needs to be more/different support for type-checking, please create a new issue,  and label it "meeting:developer" for further discussion.

**Closed by pixelzoom** 2020-06-09 22:15 UTC
Labels: status:ready-for-review
