### ISSUE TITLE
Small lines appear at points of population graph

### ISSUE THREAD

**Issue by stemilymill** [phetsims/natural-selection#292] opened 2021-07-01 22:20 UTC
**Test device**
Dell laptop & Surface

**Operating System**
Win10

**Browser**
Chrome 91.0.4472.124
(not able to reproduce on chrome os)

**Problem description**
For https://github.com/phetsims/QA/issues/662
Occurs in published version and phet-io version.

As the population graph moves along, small lines briefly appear at the points of the graph, disappearing when the next stage of the generation clock enters the frame

**Steps to reproduce**
In either Intro or Lab screen, select traits and after a few generations, add environmental factors in order to create a stable population

For instance, summer + brown fur+ wolves + limited food
Or summer + brown fur +long teeth + wolves + tough food

The easiest and fastest way to observe the behavior is to hold fast forward button and not zoom the graph in, but the behavior appears in regular speed as well.

**Visuals**
![natural selections little lines appear in pop graph](https://user-images.githubusercontent.com/85511101/124195474-92572180-da98-11eb-9128-cf2e28646b6b.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬
URL: https://phet.colorado.edu/sims/html/natural-selection/latest/natural-selection_en.html
Version: 1.3.1 2021-06-17 22:57:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment] 2021-07-01 23:36
This is undoubtedly a platform-specific graphics artifact, because there's nothing in the sim that is drawing these "small lines".   @jonathanolson any suggestions?

**Comment by jonathanolson** [comment] 2021-07-02 01:10
Initial hypothesis is that it's due to a browser not handling awkward cases correctly (perhaps there's a short almost-degenerate line? perhaps things are almost aligned but not?)

I'd either:

1. Try rounding things to every 1e-5 units (or jittering by random small amounts), changing line cap/joins, etc., if it's a stroked path that's causing this.
2. Try to inspect/reproduce a very specific path. Does it only happen while animating, or can we reproduce it to investigate statically? Then examine the path if so. Does it happen when paused?
3. Search chromium bug tracker for similar bugs

Let me know if I should look into it directly.

**Comment by pixelzoom** [comment] 2021-07-02 14:47
I am unable to reproduce this Win10 and Chrome 91.0.4472.124 (the reported configuration). Here's my info from the "Report a Problem" menu item:

<details>
<summary>Troubleshooting information</summary>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.4.0-rc.1 2021-06-21 23:54:30 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Language: en-US
Window: 1037x814
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

@stemilymill does this problem go away if you resize your browser window?

@jonathanolson are you able to reproduce this?

@amanda-phet is this issue blocking for the 1.4 release?

**Comment by stemilymill** [comment] 2021-07-02 14:56
@pixelzoom this still occurs when I resize the browser window, and I just replicated it in Edge 91.0.864.59 but have not replicated in any other config

**Comment by amanda-phet** [comment] 2021-07-06 22:00
I don't think this should be blocking, since it is not necessarily specific to this simulation. I have noticed some other artifact issues (in other sims) that I've been meaning to report, and wonder if they are related, and/or if there's anything to be done about them. I do think it's annoying, but shouldn't block this release.

**Comment by jonathanolson** [comment] 2021-07-13 19:05
I'm not able to reproduce this on my Win10 + Chome 91.

**Comment by pixelzoom** [comment] 2021-07-13 19:07
@amanda-phet says this issue is not blocking.  And @jonathanolson and I cannot reproduce it, so don't have an easy path to investigating.  So I'm going to unassign and label this issue as deferred.   Hopefully it will be addressed by future browser releases.

**Comment by Nancy-Salpepi** [comment] 2022-07-13 14:22
I was able to reproduce this problem in the PhET brand and PhET-iO standalone dev version 1.5 with Win10 + chrome. It doesn't happen with every generation. Many generations can pass (10-20) without me noticing any lines. 
I'm going to try and reproduce with mac + chrome.

**Comment by pixelzoom** [comment] 2022-07-13 14:45
Thanks @Nancy-Salpepi.  Moving this issue back to "deferred", hoping it will resolve itself in a future browser release, or some other scenery fix.

**Comment by pixelzoom** [comment] 2023-07-28 22:23
Could someone from QA please test to see whether this is still a problem?  I do not have a suitable test device.  Please indicate the OS and Chrome versions that you used to test.

**Comment by KatieWoe** [comment] 2023-07-28 22:40
I wasn't able to reproduce it, but I'll let @Nancy-Salpepi take a look since she was able to reproduce it before.

**Comment by Nancy-Salpepi** [comment] 2023-07-31 12:49
I still see the artifacts with Win10 + chrome 115, but very rarely. I'm not even sure if users would notice. 
I don't think it is worth the time to explore fixing this, especially since @KatieWoe didn't see it with Win11.

**Comment by pixelzoom** [comment] 2023-07-31 14:29
Thanks @Nancy-Salpepi.  This issue is not noticable, does not affect uability, and we're unlikely to address it.  So I'm going to close this issue as "won't fix".

**Closed by pixelzoom** 2023-07-31 14:29 UTC
Labels: priority:5-deferred
