### ISSUE TITLE
Population data does not clip properly when scrolling through generations

### ISSUE THREAD

**Issue by phet-steele** [phetsims/natural-selection#146] opened 2020-07-31 00:36 UTC
It looks like data from "further down" the x axis gets "squished" onto the chart when scrolling through generations. In the below screenshots, notice in the Before screenshot that the 5th generation shows the pop. at ~500, and the 6th generation is ~1400. Once you scroll backwards to view the 1st generation (and hide the 6th generation) in the After screenshot, the drawn section of the 6th generation does not get clipped correctly and gets drawn over the 5th gen data, making it tricky to read.

Up to @amanda-phet to decide if this has a problematic pedagogical impact and if it should be addressed before the prototype release. There is no setup for this to occur; it will happen every time you scroll through generations and occurs for all data types, not just "Total".

**Before:**
![image](https://user-images.githubusercontent.com/5863899/88985401-62ead400-d28d-11ea-8551-2302725c2bb2.png)

**After:**
![image](https://user-images.githubusercontent.com/5863899/88985707-43a07680-d28e-11ea-9f66-c3e6022ca099.png)

Seen on Win 10 Chrome 84.0.4147.89. For phetsims/QA/issues/522.

<details>
<summary>Troubleshooting Information</summary>

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.0.0-rc.1 2020-07-29 19:13:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1456x923
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by pixelzoom** [comment] 2020-07-31 03:47
No need for @amanda-phet to review, this is buggy. Should be an easy fix.

**Comment by pixelzoom** [comment] 2020-07-31 05:36
Steps to reproduce:

1. Start the sim, go to either screen
2. Press "Add a Mate" button.
3. Wait for bunnies to take over the world, close dialog
4. Press left arrow button for Generation below the Population graph

**Comment by pixelzoom** [comment] 2020-08-03 23:22
I also discovered that PopulationPlotNode does not handle the case where a count remains constant for > 6 generations, and we need to connect 2 points where p1.x < xRange.min and p2.x > xRange.max.   I haven't seen that happen, but it could.

**Comment by pixelzoom** [comment] 2020-08-04 01:48
I totally rewrote `PopulationPlotNode.plotPoints` to handle all possible datasets.  So it's now less specific to Natural Selection, and more general, in case we ever need to reuse it elsewhere (e.g. in griddle). 

@amanda-phet and @phet-steele please have a look at this in [1.1.0-dev.3](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.3/phet/natural-selection_en_phet.html), with high priority since it's a major change.

**Comment by pixelzoom** [comment] 2020-08-04 01:52
Cherry-picked to 1.0 (prototype) branch.

**Comment by pixelzoom** [comment] 2020-08-05 21:22
@amanda-phet  if you could prioritize review of this issue, it would be great. It needs to be completed before I can publish the next RC for the prototype.

**Comment by amanda-phet** [comment] 2020-08-05 22:47
Looks good to me.

**Comment by phet-steele** [comment] 2020-08-05 22:51
The original issue seems fine, but I'm seeing weird behaviour.

1. Intro screen, enable at least "brown fur" in the population graph
2. Add a mate
3. Run until gen 3, then add limited food
4. Run until gen 5, then add the fur mutation (doesn't matter which is chosen to be dominant)
5. Let the sim run for 6+ generations and until there are >0 brown fur bunnies.

In the below screenshots, you'll notice that when I am viewing the data for gen 6+, everything looks fine. But as soon as I scroll and clip gen 6, the data is incorrect (the dashed line should be at 0, not 4)

Before:
![image](https://user-images.githubusercontent.com/5863899/89470696-a0da7300-d739-11ea-9cfd-034d69fdc498.png)

After:
![image](https://user-images.githubusercontent.com/5863899/89470733-b2bc1600-d739-11ea-8ecd-5a9919c2d4b0.png)

This was seen on Win 10 Chrome using https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.3/phet/natural-selection_all_phet.html

**Comment by pixelzoom** [comment] 2020-08-07 23:54
Good catch @phet-steele.  Fixed in the above commit.  Please verify in master.

**Comment by pixelzoom** [comment] 2020-08-10 21:09
@phet-steele if you don't have VPN access, you can test in https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.4/phet/natural-selection_en_phet.html.

**Comment by phet-steele** [comment] 2020-08-10 22:31
https://github.com/phetsims/natural-selection/issues/146#issuecomment-669583613 looks resolved in 1.1.0-dev.4.

**Comment by pixelzoom** [comment] 2020-08-10 23:32
Excellent, thanks @phet-steele.  Since the next RC is going to be published out of master, I'm going to go ahead and close this issue.

**Closed by pixelzoom** 2020-08-10 23:32 UTC
Labels: status:blocks-sim-publication, type:bug
