### ISSUE TITLE
State wrapper bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#74] opened 2020-05-09 00:29 UTC
When setting state on the 5th generation of bunnies after adding a mate in this link:

http://localhost:8080/phet-io-wrappers/state/?sim=natural-selection&phetioValidateTandems&phetioDebug&secondsPerGeneration=1&screens=2

. . . there is an obfuscated error in the state wrapper. Setting a debugger in the `catch` in phetioCommandProcessor.processCommands()` lead me to the error that was being thrown in ObservableArray.push:

`      throw new Error( 'duplicates are not allowed' );`

This is for dead bunnies:

```
Error: duplicates are not allowed
    at BunnyArray.push (ObservableArray.js:220)
    at isAliveListener (BunnyCollection.js:91)
    at TinyEmitter.emit (TinyEmitter.js:69)
    at BooleanProperty._notifyListeners (Property.js:270)
    at PhaseCallback.listener (Property.js:320)
    at PhetioStateEngine.attemptToApplyPhases (PhetioStateEngine.js:337)
    at PhetioStateEngine.undeferAndNotifyProperties (PhetioStateEngine.js:269)
    at PhetioStateEngine.setState (PhetioStateEngine.js:205)
    at PhetioEngineIO.implementation (PhetioEngineIO.js:221)
    at PhetioCommandProcessor.processCommand (phetioCommandProcessor.js:267)

```

I wanted to note it here, because I ran into it during unrelated testing for https://github.com/phetsims/phet-io/issues/1634, but I don't think it is related to that (as shelving those changes could still reproduce this problem).

Tagging @pixelzoom.

**Comment by pixelzoom** [comment] 2020-05-09 16:22
Reproduced locally.

**Comment by pixelzoom** [comment] 2020-05-09 16:37
I'm guessing that this is related to state being restored for elements of BunnyCollection. It has BunnyGroup (`bunnyGroup`) and ObservableArrays (`liveBunnies`, `deadBunnies`), where every element in  bunnyGroup is contained in either `liveBunnies` or `deadBunnies`.  I tried setting `phetioState: false` for both `liveBunnies` or `deadBunnies`, and that clears up this specific Error.  But then a new Error occurs:

```
Uncaught Error: Assertion failed: bunny age 6 exceeded maximum 5
    at window.assertions.assertFunction (assert.js:22)
    at BunnyCollection.js:211
    at Array.forEach (<anonymous>)
    at BunnyCollection.ageAllBunnies (BunnyCollection.js:207)
    at BunnyCollection.stepGeneration (BunnyCollection.js:188)
    at NaturalSelectionModel.js:121
    at TinyEmitter.emit (TinyEmitter.js:69)
    at DerivedProperty._notifyListeners (Property.js:270)
    at DerivedProperty.set (Property.js:170)
    at listener (DerivedProperty.js:71)
```

**Comment by pixelzoom** [comment] 2020-05-09 16:56
I think I understand why ObservableArrays `this.liveBunnies` and `this.deadBunnies` need to be `phetioState: false`.  They are populated by the listener to `this.bunnyGroup`.  So if their state is restored, we'll have duplicates.

For the new error (`bunny age 6 exceeded maximum 5`) it looks to me like Bunny elements are not fully restored before `BunnyGroup.elementCreatedEmitter` fires.   Specifically the ageProperty has not been restored, so it's ending up in the `liveBunnies` array.  Then `BunnyCollection.ageAllBunnies` fails because it encounters an invalid state - a bunny that should never have gotten that old.  @zepumph does this seem like a plausible explanation?  If so, why are elements of a PhetioGroup not fully restored before firing `elementCreatedEmitter`?

**Comment by pixelzoom** [comment] 2020-05-09 17:07
Questions:

* When a PhetioGroup is restored, is `elementCreatedEmitter` fired for each element in the group?
* Is each element in the group guaranteed to be fully restored (all state, all Properties) before its membership in the group is restored?

**Comment by pixelzoom** [comment] 2020-05-09 17:31
> When a PhetioGroup is restored, is elementCreatedEmitter fired as each element's group membership is restored?

I'm going to assume that the answer is "yes", so I'll need to handle both live and dead bunnies in the listener for `bunnyGroup.elementedCreatedListener`.  That change has been made in the above commit. 

But I'm still getting the "bunny age 6 exceeded maximum 5" assertion failure, and I can't determine how that is happening.

Pro tip: This is easiest to test with:

`phet-io-wrappers/state/?sim=natural-selection&phetioValidateTandems&phetioDebug&secondsPerGeneration=1&maxAge=2`

... where `maxAge=2` makes bunnies die after 2 generations instead of 5 generations (the default).

**Comment by pixelzoom** [comment] 2020-05-09 17:42
In the above commit, I added an assertion to the beginning of `ageAllBunnies`:

```js
    assert && assert( _.every( this.liveBunnies.getArray(), bunny => bunny.isAliveProperty.value ),
      'liveBunnies contains one or more dead bunnies' );
```

... and this assertion is failing as soon as there are dead bunnies.   So dead bunnies are being added to `liveBunnies`.

**Comment by pixelzoom** [comment] 2020-05-09 17:52
In the above commits, I realized that Bunny `age` does not need to be a Property, since nothing observes it.  So I changed from `this.ageProperty` to `this.age`, and added it to state object.   This results in no change to the "exceeds maxAge" Error.

**Comment by pixelzoom** [comment] 2020-05-09 18:10
In the above commit, I replaced Bunny `this.isAliveProperty` with `this.alive` and `this.diedEmitter`.  This makes more sense than a Property, since the state only changes once, from living -> dead. 

This resolved the "exceeds maxAge" exception.  But I'm still curious about what the problem was with using a Property, as well as answers to the general questions in https://github.com/phetsims/natural-selection/issues/74#issuecomment-626206851.

**Comment by zepumph** [comment] 2020-05-14 01:41
After the above commits, state is working in NS. I would love to discuss each problem that I found, and make sure that @pixelzoom get's eyes on the changes and agrees with them. 

1. BunnyCollection.stepGeneration() does work that shouldn't be done on state, and as a result we were getting an inconsistent downstream state where double or even triple bunnies were being created (one from the state engine, and one from steping the generation when that Property changes on state set). Limiting this fixed once occurrence of countProperty being off from PhetioGroup._array.length.
2. I ran into trouble with created BunnyNodes for already dead bunnies. This is because `this.diedEmitter` isn't called when an already dead bunny is reconstituded in the state engine. My workaround may not be the best way to proceed, but it bypassed the assertion and extra BunnyNodes. Another way would potentially be to fire the `diedEmitter` when adding the newly created dead bunny to the deadBunnies list. I don't know what is better. Up to you @pixelzoom!
1. After all the changes, we can remove the assertion workaround in `assertValidCounts`.


@pixelzoom please review.

**Comment by pixelzoom** [comment] 2020-05-14 02:02
Thanks @zepumph, this all looks really good. Closing.

**Closed by pixelzoom** 2020-05-14 02:02 UTC
Labels: dev:phet-io, phet-io:save-and-load, status:ready-for-review
