### ISSUE TITLE
Sprites are not drawn when sim is launched while paused (Safari 14.0)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#243] opened 2020-09-23 19:32 UTC
For https://github.com/phetsims/QA/issues/551. Seen on Mac 10.15 Safari but not on Mac 10.15 Chrome.
If you launch the sim from Studio while it is paused, the rabbits do not seem to appear in the play area. If you hit the play button they come up. If the sim is not paused when launched this doesn't seem to happen.
![blankstart](https://user-images.githubusercontent.com/41024075/94060370-14474b00-fda1-11ea-9872-e9d4d65673c4.gif)

**Comment by KatieWoe** [comment] 2020-09-23 19:35
Just narrowed it down a bit. It depends on what browser opens it, not what browser made it. If you download it as an html and open in Chrome it works as expected. The same file opened in Safari shows the bug.

**Comment by pixelzoom** [comment] 2020-09-23 19:42
It sounds like there may be some issue with the html file only being compatible with the browser that was used to create it.

@KatieWoe a couple of questions:

(1) If the file was created in Safari, then opened in Safari, is there a problem?

(2) If the files was created in Safari, then opened in Chrome, is there a problem?

**Comment by KatieWoe** [comment] 2020-09-23 19:43
If created in safari and opened in safari, there is the bug.
If created in safari and opened in chrome, there is no bug.

**Comment by pixelzoom** [comment] 2020-09-23 19:51
Thanks @KatieWoe.  So it sounds like the problem is specific to Safari, and present regardless of which browser was used to create the html file.

**Comment by KatieWoe** [comment] 2020-09-23 22:08
This looks like it might be seen for a split second in the State wrapper in Safari as well, but it is hard to tell.

**Comment by loganbraywork** [comment] 2020-09-23 22:24
Does not appear on Windows 10 Firefox

**Comment by samreid** [comment] 2020-09-24 17:45
I think the sprites are not getting triggered to draw when the sim launches.  @jonathanolson is there a way to trigger that draw?  I tried adding this to OrganismSprites constructor, but it didn't trigger a redraw:

```js
    Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( () => {
      this.update();
    } );
```

**Comment by pixelzoom** [comment] 2020-09-24 17:56
If that's the problem... Any thoughts on why the sprites are not getting redrawn only on Safari?

**Comment by pixelzoom** [comment] 2020-09-24 18:08
I haven't tested this yet, but if it's an issue of updating sprite, this is probably the way to do so, in NatrualSelectionScreenView.js:

```diff
  step( dt ) {
-    if ( this.model.isPlayingProperty.value ) {
+    if ( this.model.isPlayingProperty.value || phet.joist.sim.isSettingPhetioStateProperty.value ) {

      // Sim.js calls model.step before view.step. So after all of the model elements have been updated, this
      // updates the view of their corresponding sprites.
      this.environmentNode.updateSprites();
    }
  }
```

**Comment by pixelzoom** [comment] 2020-09-24 18:18
The above fix did not fix the problem.

**Comment by pixelzoom** [comment] 2020-09-24 18:21
Steps to reproduce:

1. Run the sim in Studio
2. Pause the sim
3. Press the "Launch" button.
4. Note that no sprites are drawn in the launched sim.
5. Press the step button in the launched sim, and note that the sprites get drawn.

**Comment by pixelzoom** [comment] 2020-09-24 18:46
Next attempt was to add `this.updateSprites();` to the end of EnvironmentNode's constructor. That did not fix the issue.

**Comment by pixelzoom** [comment] 2020-09-24 19:04
This change to NaturalSelectionScreenView `step` fixes the problem:

```diff
  step( dt ) {
-    if ( this.model.isPlayingProperty.value ) {
-
-      // Sim.js calls model.step before view.step. So after all of the model elements have been updated, this
-      // updates the view of their corresponding sprites.
      this.environmentNode.updateSprites();
-    }
  }
```

But then sprites are being continually updated when the sim is paused.

**Comment by pixelzoom** [comment] 2020-09-24 19:49
9/24/2020 design meeting:

If I run with `?webgl=false`, this problem goes away.  So this feels like something that is scenery specific (with either Sprites.js or WegGL), and @samreid agrees.  

Assigning to @jonathanolson with high priority.  The next RC needs to be published by Monday 9/28 to stay on track.

**Comment by pixelzoom** [comment] 2020-09-24 21:18
In Slack, @jonathanolson discovered that this problem is specific to Safari 14:

> Jonathan Olson  2:26 PM
I can't reproduce this on Safari 13.0.4 (slightly older)
Or I'm doing something horribly wrong
Sounds like I should OS update?
> 
> Jonathan Olson  2:42 PM
Reproducing on Safari 14

**Comment by jonathanolson** [comment] 2020-09-24 22:16
I'm a bit at a loss of what might be causing this. I've verified that the images have the correct dimensions and contents, the spritesheet is correctly filled with the data, the data in the WebGL-side texture is correct, all of the uniforms being passed into the draw call seem correct, the buffer is filled with what looks like correct data... but nothing is being drawn.

Committed a workaround above, @pixelzoom can you verify that it resolves the NS issue?

**Comment by samreid** [comment] 2020-09-24 22:20
Should we use the `animationFrameTimer` instead of the `stepTimer` so that it will repaint even if the simulation is set to `sim.activeProperty.value = false` or is otherwise not stepping?

**Comment by jbphet** [comment] 2020-09-24 22:34
During today's developer meeting, we thought it would be wise to double check that this problem does not afflict the energy chunks in Energy Forms and Changes, since it is in the process of being released.  I checked version 1.4.0-rc.2 on Mac OS 10.12.6, and created several scenarios where there were lots of energy chunks, and all launched fine when paused.

**Comment by pixelzoom** [comment] 2020-09-24 23:25
@jonathanolson Yes, the workaround does resolve the problem in Natural Selection.  Is the additional change that @samreid made OK?  Is this ready to cherry-pick for natural-selection 1.2?

**Comment by jonathanolson** [comment] 2020-09-25 01:43
> Is the additional change that @samreid made OK? Is this ready to cherry-pick for natural-selection 1.2?

Yes and yes.

**Comment by pixelzoom** [comment] 2020-09-25 19:30
Patched in 1.2 branch, ready for verification in the next 1.2 RC.   

Verify on macOS + Safari 14, using these steps:

1. Run the sim in Studio
2. Pause the sim
3. Press the "Launch" button.
4. Verify that the sprites (bunnies, etc.) are drawn correctly in the launched sim

**Comment by KatieWoe** [comment] 2020-09-26 16:23
Looks fixed in Studio in rc.2. However, in the State wrapper, I still see a second of a blank play area. @pixelzoom feel free to close if this isn't a concern.
![oddityinstate](https://user-images.githubusercontent.com/41024075/94345326-527f7d00-ffe2-11ea-981f-29b79fe5397c.gif)

**Comment by pixelzoom** [comment] 2020-09-27 14:14
The workaround for this problem in scenery was to force a redraw in the next animation frame.  That's why you're seeing the bunnies etc. draw 1 frame later in some cases.   This seems acceptable for the #208 1.2 release.  I'll keep this issue open so that we can revisit for the 1.3 release, and perhaps even find a solution instead of a workaround.

**Comment by ariel-phet** [comment] 2020-10-05 16:52
Totally acceptable. closing

**Closed by ariel-phet** 2020-10-05 16:52 UTC
Labels: dev:phet-io, type:bug
